### ISSUE TITLE
Duplicates in Finding filters

### ISSUE THREAD

**Issue by quirinziessler** [DefectDojo/django-DefectDojo#10401]
The findings filter has duplicates in regards of filtering for the creation of findings.
![image](https://github.com/DefectDojo/django-DefectDojo/assets/19915467/43bec233-b797-4637-a557-bff2082eba35)

1. there is a filter to define a timeframe within "Date discovered" 
![image](https://github.com/DefectDojo/django-DefectDojo/assets/19915467/cf92f5bf-dfb0-4234-a261-be81f3a6861e)
2. there are three filter options to define "before", "on" and "after"
![image](https://github.com/DefectDojo/django-DefectDojo/assets/19915467/d3bfa992-aa44-424a-8b7d-504f27f58580)

Is there any purpose behind this duplicates? And if so, why is my second point simply described with "on" and not a bit detailed like "discovered on"?

I looked at PRs in the past and think this came with #9642. Can you maybe bring a bit light into this @FelixHernandez?

**Comment by mtesauro** [comment]
FWIW, I don't think these are really duplicates - rather optional filters that make sense in certain circumstances. I do think there could be better usability around the UI side of these so feel free to do a PR to make their use more clear.

It's been a while since that PR but from what I recall:
* That PR allowed you to provide a range for findings using the "Date Discovered" form fields e.g. 2024-05-01 to 2024-05-15
  * Looks like the lighter text inside the filter form fields for "Date Discovered" probably could have better labels like "From" and "To"
* The 3 (On, Before, After) is more date filtering options
  * On - Findings on that date e.g. Findings on 2024-05-15
  * Before - Findings before that date e.g. Findings before 2024-05-15
  * After - Finding after that date e.g. Findings after 2024-05-01
  * I believe these are meant to be mutually exclusive aka you should only use one of On, Before, After
 
My recollection of this PR was the general idea was: If you were trying to synchronize DefectDojo with some other system (e.g. polling for findings), its much easier to ask by date then to have to track a finding number on the system doing the polling. Instead, that polling system would just have to know that it has all finding up to {date} and then make a call to all findings after {date} going forward.

HTH

**Comment by quirinziessler** [comment]
Thanks for looking into this @mtesauro!

I understand the feature and also think this is helpful as I discovered this by using the feature. But they work same for me. An example below:

Using the time range filter like this
![image](https://github.com/DefectDojo/django-DefectDojo/assets/19915467/1f744b78-374c-45a5-8227-43d454ea294b)
returns the same results as this via the "after"
![image](https://github.com/DefectDojo/django-DefectDojo/assets/19915467/37fa7413-a8d0-4a35-bfbd-90a06cf25aeb)

If I use the time range filter like this, I can specify the "on" date same as via the "On" filter:
![image](https://github.com/DefectDojo/django-DefectDojo/assets/19915467/d6a4facc-e9c2-4aaa-9b75-ab5227091e24)
![image](https://github.com/DefectDojo/django-DefectDojo/assets/19915467/7e3f9bcc-44ad-41cf-91a7-71a338dd05f5)

I did a PR that adds some more description to the "on", "before" and "after" and adds a timeframe filtering for the mitigated field. Would be happy if you can look into this.

**Comment by manuel-sommer** [comment]
THis can be closed @quirinziessler
