### ISSUE TITLE
Duplicated Engagement

### ISSUE THREAD

**Issue by afagund** [DefectDojo/django-DefectDojo#10607]
I am seeing few engagements being duplicated (2 or more distinct engagements with the same name) when importing Trivy reports using the trivy-dojo-report-operator (https://github.com/telekom-mms/trivy-dojo-report-operator/)

**Steps to reproduce**
1. Import Trivy reports via trivy-dojo-report-operator
2. Go to All Engagements on DefectDojo
3. Check if there is more than one engagement with the same name

**Expected behavior**
Should not exist more than one engagement with a specific name

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
 - DefectDojo version 2.34.4 running on Kubernetes via Helm chart revision 1.6.130

**Screenshots**
![image](https://github.com/user-attachments/assets/00e99738-71da-43d9-906d-23fdad36b3e0)

**Comment by manuel-sommer** [comment]
Hi @afagund 

I am also using the trivy operator and don't have this issue. DefectDojo has V 2.35.3. 
Maybe you open an issue in the trivy operator project?

**Comment by afagund** [comment]
@manuel-sommer 

I already opened a issue for them, but no answer. But I would like to know from a DefectDojo perspective why it's allowing duplicated engagements if those are being created via API.

**Comment by afagund** [comment]
We updated DefectDojo to 2.36.4 and still the same issue.

The engagements are being created via API using the following params:

`{
    "active": True,
    "verified": False,
    "close_old_findings": False,
    "close_old_findings_product_scope": False,
    "push_to_jira": False,
    "minimum_severity": "Info",
    "auto_create_context": True,
    "deduplication_on_engagement": True,
    "scan_type": "Trivy Operator Scan",
    "engagement_name": "argocd",
    "product_name": "saas",
    "product_type_name": "internal-services",
    "environment": "Development",
    "test_title": "test",
    "do_not_reactivate": True,
}`

**Comment by manuel-sommer** [comment]
What if you choose "auto_create_context" = False and make sure that the engagement_name and product_name exists in advance? That's how I do it.

**Comment by mtesauro** [comment]
FWIW, I just tested trivy via the API + UI and those work as expected. There appears to be some sort of issue in the upstream project (trivy-dojo-report-operator) so it's probably best to work directly with that project. 

Since I've never used that operator, I can't comment on what may be going on.

Perhaps try to replicate the calls that the operator is making to DefectDojo's API and see if modifications to them stop the behavior you're seeing.  I could be how the requests are being made, the options/parameters provided or something else but at least you might be able to replicate the behavior and provide more details to trivy-dojo-report-operator.

**Comment by afagund** [comment]
@mtesauro 

We are talking about pure API requests being sent to DefectDojo at api/v2/reimport-scan/. If we have a problem, it must be with the DefectDojo API not handling the requests correctly.

**Comment by mtesauro** [comment]
@afagund 
> We are talking about pure API requests being sent to DefectDojo at api/v2/reimport-scan/. If we have a problem, it must be with the DefectDojo API not handling the requests correctly.

Yes, if 3rd party code calls the API correctly to create 2 engagements, DefectDojo will do the right thing and create 2 engagements.

Since I don't know what endpoints or how the API is being called by trivy-dojo-report-operator, I can't say if it's duplicating requests or not.

I can say that using the API with curl, I can successfully create a single engagement with a single trivy test using a trivy output. 

I can also say that the unit tests we have for trivy, the UI and API tests we have as GH Actions continue to pass.

If you can demonstrate how the API isn't correctly handling the parameters provided, then there might be something to address here.  Please feel free to reopen this issue if you find this is the case.

I'm sorry that some code that a 3rd party wrote to integrate with the DefectDojo API isn't working as you expect but since 
trivy-dojo-report-operator isn't part or supported by the DefectDojo maintainers, I'm not sure what more can be done without specific details on how the API isn't working correctly beyond what's been provided currently.

Again, this seems like an issue that could be much better addressed by the contributors to trivy-dojo-report-operator. Its unfortunate that they haven't answered your issue but there's not much this project can do do remedy that.

**Comment by afagund** [comment]
@mtesauro as i said, I analyzed the code and the only thing there is a request being sent to DefectDojo with the parameters that I have provided. They are communicating with DefectDojo via API, how can this not be an issue with DefectDojo? Also, we are seeing an engagement being created with the same name twice, why is that allowed by DefectDojo? We are not bypassing the API, for example, going directly to the database and creating the engagement, again, we are doing this via API. Please, if you don't have an answer for this, can you escalate to someone who understand better the code which handle the imports? It looks like a race condition, that's probably the reason you are not catching the problem sending a single request to the API, it's probably not fast enough. The automation will perform several imports in a matter of seconds.

**Comment by Maffooch** [comment]
Hi @afagund 

The engagement model in DefectDojo does not enforce any sort of uniqueness across instances. This has been the design of the Engagement model since the inception of DefectDojo. Unfortunately, making a large change like this to the engagement model would likely break automation for many users of DefectDojo

Hopefully this is helpful!

**Comment by afagund** [comment]
Hi @Maffooch

Please, can you tell in which situation we are expected to have 2 or more engagements with the same name? It seems like it should always use the same engagement if it already exists.

Really appreciate your response!

**Comment by Maffooch** [comment]
I was not involved in the initial design, but I would imagine that the reasoning was based on having the same engagement name across products, or perhaps from year to year
