### ISSUE TITLE
Automatically fill in CWE

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1119]
**Is your feature request related to a problem? Please describe**
Example: Scans import do not necessarily include the CWE related to the CVE reported, leaving the analyst looking it up and filling it manually (unless I missed something).

**Describe the solution you'd like**
If a finding has a CVE number, attempt to find the related CWE by querying a site like cvedetails.com and update automatically.

**Describe alternatives you've considered**
None so far.

**Additional context**
Add any other context, screenshots, sketch, code snippet, etc. about the feature request here.

**Comment by valentijnscholten** [comment]
I've been thinking about the same when the severity is missing. There's a github repo containing all CVEs in json format that might be helpful: https://github.com/olbat/nvdcve

**Comment by ptrovatelli** [comment]
could be nice but beware that defectDojo should still work in an isolated environment:
- add a configuration to allow offline working (should be offline by default to avoid problems)
- handle a default list of cwe that's commited in DD's github repo so that updating defectDojo will transparently update the known cwe. Ideally automate the updation of this list maybe with travis?

**Comment by jvz** [comment]
In order to cache or use the CVE data offline, perhaps we can introduce a new model for it? This could be useful for linking metadata about a CVE to findings from https://github.com/CVEProject/cvelist directly. That seems like a lot of data to add to this repository directly, though if you're suggesting a cache of mappings between CVEs and CWEs, then that might be more feasible.

**Comment by madchap** [comment]
Keeping it open.
