### ISSUE TITLE
Regarding setting metadata.

### ISSUE THREAD

**Issue by atharva1051** [DefectDojo/django-DefectDojo#11305]
Hi I need to set some metadata for a product type which sould be queryable by the API is that possible?
For eg product type we have to map with some other external id, since we cant manually set the product type id, anywhere we can set? Preferably not description because that is not queryable

**Comment by mtesauro** [comment]
Product Types don't support metadata only products, findings and endpoints.

Besides  putting something in the description, Product Type doesn't really support attaching data to them like tags or metadata

If you look at what the API returns for a Product Type (this is from the demo instance), it's not much:
```
{
  "id": 4,
  "name": "Juice Shop",
  "description": "shop",
  "critical_product": false,
  "key_product": false,
  "updated": "2024-11-21T21:02:53.440257Z",
  "created": "2024-11-21T21:02:53.440284Z",
  "members": [
    1
  ],
  "authorization_groups": [],
  "prefetch": {}
}
```

Product Types are really just a way to group related Products so don't hold additional data by design.

**Comment by atharva1051** [comment]
Okay Thanks for the quick response, we will look to create this metadata somewhere outside.
 Good Day!
