### ISSUE TITLE
broken queryset tag list when finding with tags becomes a template and then edited

### ISSUE THREAD

**Issue by nwse-strm-suer** [DefectDojo/django-DefectDojo#1251]
**Bug description**
When a new finding is edited and saved including tags, a newly created finding template will reuse these tags (correct). But when the finding template is edited, the display of the queryset list of tags is broken. The source code reveals:

`<option value="&lt;queryset [&lt;tag: baz&gt;" selected>&lt;queryset [&lt;tag: baz&gt;</option>`

**Steps to reproduce**
1. edit a findings and add tags
2. save finding
3. make finding a template
4. edit finding template
5. find broken tags list at the bottom of the page (see screenshots)

**Expected behavior**
no broken tag list

**Screenshots**
![2019-06-12 defectdojo edit_finding_adding_tags](https://user-images.githubusercontent.com/51413804/59361965-00eea880-8d33-11e9-8007-4660b7b18390.png)
![2019-06-12 defectdojo edit_template_broken_tags_list](https://user-images.githubusercontent.com/51413804/59361973-04822f80-8d33-11e9-927a-f793d3041082.png)

**Comment by nwse-strm-suer** [comment]
I am not sure, but maybe it is related to the template tags enhancement: https://github.com/DefectDojo/django-DefectDojo/issues/890

**Comment by devGregA** [comment]
@devEricA please validate and investigate.

**Comment by devEricA** [comment]
@devGregA The problem is in the structure of template's tags, specifically in the mktemplate method of Finding. When using sys.stderr to check the data of finding tags and template tags, I noticed that the data for finding's tags was good, but the data template's tags were broken. @Maffooch and I tried several methods of copying the finding's tags into the template's tags, but all have resulted in some form of the broken tags. I think somehow we have to access the tag model of the template in order to fix this problem.
