### ISSUE TITLE
Deduplication stopped working (APIv2)

### ISSUE THREAD

**Issue by wurstbrot** [DefectDojo/django-DefectDojo#1478]
I am using api v2 with a docker-compose setup with current dev branch. I am trying to import dependency check results.

Deduplication is not tiggered.  I guess it has somehow been triggered before.
```
nginx_1         | 2019/08/10 14:45:01 [warn] 6#6: *691 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000006, client: 192.168.48.1, server: , request: "POST /api/v2/import-scan/ HTTP/1.1", host: "localhost:8080"
uwsgi_1         | /usr/local/lib/python3.5/site-packages/django/db/models/fields/__init__.py:1363: RuntimeWarning: DateTimeField Test.target_start received a naive datetime (2019-08-10 00:00:00) while time zone support is active.
uwsgi_1         |   RuntimeWarning)
uwsgi_1         | /usr/local/lib/python3.5/site-packages/django/db/models/fields/__init__.py:1363: RuntimeWarning: DateTimeField Test.target_end received a naive datetime (2019-08-10 00:00:00) while time zone support is active.
uwsgi_1         |   RuntimeWarning)
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
uwsgi_1         | applying rules
nginx_1         | 192.168.48.1 - - [10/Aug/2019:14:45:03 +0000] "POST /api/v2/import-scan/ HTTP/1.1" 201 240 "-" "Java/1.8.0_222" "-"
uwsgi_1         | [pid: 439|app: 0|req: 5/5] 192.168.48.1 () {40 vars in 722 bytes} [Sat Aug 10 14:45:01 2019] POST /api/v2/import-scan/ => generated 240 bytes in 2006 msecs (HTTP/1.1 201) 4 headers in 128 bytes (1 switches on core 0)
uwsgi_1         | [pid: 439|app: 0|req: 6/6] 192.168.48.1 () {36 vars in 524 bytes} [Sat Aug 10 14:45:03 2019] GET /api/v2/products/?name=test3 => generated 488 bytes in 14 msecs (HTTP/1.1 200) 4 headers in 134 bytes (1 switches on core 0)
nginx_1         | 192.168.48.1 - - [10/Aug/2019:14:45:03 +0000] "GET /api/v2/products/?name=test3 HTTP/1.1" 200 488 "-" "Java/1.8.0_222" "-"
uwsgi_1         | [pid: 439|app: 0|req: 7/7] 192.168.48.1 () {36 vars in 562 bytes} [Sat Aug 10 14:45:03 2019] GET /api/v2/engagements?product=1&limit=50&offset=0 => generated 0 bytes in 1 msecs (HTTP/1.1 301) 3 headers in 153 bytes (1 switches on core 0)
nginx_1         | 192.168.48.1 - - [10/Aug/2019:14:45:03 +0000] "GET /api/v2/engagements?product=1&limit=50&offset=0 HTTP/1.1" 301 0 "-" "Java/1.8.0_222" "-"
uwsgi_1         | [pid: 439|app: 0|req: 8/8] 192.168.48.1 () {36 vars in 564 bytes} [Sat Aug 10 14:45:03 2019] GET /api/v2/engagements/?product=1&limit=50&offset=0 => generated 938 bytes in 14 msecs (HTTP/1.1 200) 4 headers in 134 bytes (1 switches on core 0)
nginx_1         | 192.168.48.1 - - [10/Aug/2019:14:45:03 +0000] "GET /api/v2/engagements/?product=1&limit=50&offset=0 HTTP/1.1" 200 938 "-" "Java/1.8.0_222" "-"
uwsgi_1         | [pid: 439|app: 0|req: 9/9] 192.168.48.1 () {48 vars in 1107 bytes} [Sat Aug 10 14:45:04 2019] GET /alerts/count => generated 12 bytes in 28 msecs (HTTP/1.1 200) 4 headers in 114 bytes (1 switches on core 0)
nginx_1         | 192.168.48.1 - - [10/Aug/2019:14:45:04 +0000] "GET /alerts/count HTTP/1.1" 200 12 "http://localhost:8080/api/key-v2" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/76.0.3809.87 Chrome/76.0.3809.87 Safari/537.36" "-"
celeryworker_1  | [2019-08-10 14:45:07,523: INFO/MainProcess] Received task: dojo.tasks.async_dupe_delete[b5f16008-4738-432b-88d7-00db23867ebf]  
celeryworker_1  | [2019-08-10 14:45:07,524: INFO/MainProcess] dojo.tasks.async_dupe_delete[b5f16008-4738-432b-88d7-00db23867ebf]: delete excess duplicates
celeryworker_1  | [2019-08-10 14:45:07,529: INFO/MainProcess] Task dojo.tasks.async_dupe_delete[b5f16008-4738-432b-88d7-00db23867ebf] succeeded in 0.00508868200085999s: None
```
It might be related to https://github.com/DefectDojo/django-DefectDojo/pull/1395 (@Maffooch)

**Comment by ptrovatelli** [comment]
@wurstbrot are you trying to deduplicate several findings within the same report, or do you upload twice the same report? can you provide a sample report for reproducing the issue? 
Thanks!

**Comment by Maffooch** [comment]
Hey @wurstbrot deduplication has to be explicitly enabled in settings for it to happen in any place now. The changes were made [here](https://github.com/DefectDojo/django-DefectDojo/pull/1395).

**Comment by wurstbrot** [comment]
Sorry for not being precise.
I use for example https://github.com/DefectDojo/sample-scan-files/blob/master/dependency_check/dependecy_check_v4.0.2.xml

I do activate dedub in system settings and I do upload multiples time.

**Comment by Maffooch** [comment]
Have you enabled the loggers associated with dedupe in settings.py? They are pretty verbose and can help narrow down the issue. Before the changes, dedupe was way too generous in passing out duplicate status. I made it a bit harder to earn it.

**Comment by wurstbrot** [comment]
I haven't, will do that tomorrow.

I thought by seeing _Received task: dojo.tasks.async_dupe_delete_ there should be also a task like _Received task: dojo.tasks.async_dupe_

**Comment by Maffooch** [comment]
Hmm. There totally should have been. Ill play around with it today and see if I can come up with something. Will keep you posted.

**Comment by Maffooch** [comment]
After further investigation, I found that if no line number is supplied in the scan, deduplication kinda falls apart. The hash code is not even computed. This falls in line very similar to #1128. We have got to come up with a better system. The largest issue is that not all scanners provide the same information. For example, the dependency check scan does not even provide a line number. How can that even be combatted? Does this mean deduplication just cannot be used in these cases?

While I was at it, I ran the dedupe unit test found in the tests folder. Deduplication is working as intended for the scans associated with that test. However, that does not mean that all scanners are working with deduplication.

**Comment by wurstbrot** [comment]
From my point of view, this smells like tool parsers might provide an optimized way for deduplication handkling and in case there is no optimized way, the default way is used.

**Comment by Maffooch** [comment]
So you're saying that each parser would have its own method of identifying duplicates, and if that fails, the system level method would take over and give it a go? That would work in the case of finding dupes with the same parser, but wouldn't really do much with findings that come from other parsers.

**Comment by wurstbrot** [comment]
the other way. the system level dedup is used, in case a parser is not having his own dedup implementation.

In this case it means, that we have to add a parser implementation for dependency check while is does not effect all other parsers.

**Comment by Maffooch** [comment]
Yeah, that could be a good idea. I suppose we could just implement on a case by case basis. Im going to stew on this for a bit.

**Comment by wurstbrot** [comment]
Tell me how I can help. This is a big problem for my production instance as it is not usable at all (or I have to switch to re-import loosing benefits of dedup).

**Comment by Maffooch** [comment]
Got an idea here. What if we made deduplication a little less strict. As it stands now, if a finding does not have a file path and line number, a hash code is not generated, and deduplication does not happen. Maybe we could rely on equality instead. This way, if findings share all the same characteristics along with line number/path being none, deduplication can still do something. What kind of issues would that bring about?

**Comment by ptrovatelli** [comment]
Hi guys; funny I was just having a thought about line number a couple of days ago: say you find a vuln in file tutu.java at line 100; before importing the file again, you have added some code before line 100, because in real life you don't just re-import always the same scan :) . So your finding is now at line 101. Bam! the deduplication will not work because the line has changed. It'll appear as if you have added a vuln and removed another one. 
If you had put some comment or even false positive information on that finding, you've lost the information. I was planning on using dedup to keep information added in findings throughout possible many scans over months/years.
To come around this, I was thinking we should make the deduplication configurable, possibly for each scanner. Or to be more precise, we should make the hash_code computation configurable. At this point I still think the dedup itself can still be basically based on hash_code. 
However in settings.py, we could configure a list of fields for each scanner that is used to compute the hash_code. What do you think? 
I don't think we need to implement a specific algorithm for each scanner which would be a terrible amount of work while we can handle this I think just with the configuration I proposed before

To fix the initial issue i presented: I was thinking of removing altogether the line number in the hash_code, so that all findings of the same kind and in the same file are seen as duplicates.

**Comment by Maffooch** [comment]
@ptrovatelli Thats a good example. With that in mind, that's closer to how deduplication works with endpoints. It's basically just checking the file path on a server. I'm in favor or simply removing line number. 

I think the configurable dedupe options would be a lot of work. Deduplication is intertwined with the save function in the Finding model. This would also bring some compatibility concerns to the table as well. How would deduplication handle findings from different parsers with different configurations? For example, Dependency Check would have the configuration of no line number would be computed in the hash, but maybe Cobalt.io does not provide CWE's. That would mean dedupes would be calculated with no line number nor CWE. Chances of that working are slim, but scenarios are possible.

**Comment by ptrovatelli** [comment]
@Maffooch I may be wrong but I don't see a problem here: 
- each parser computes the hash_code, based on it's configuration (could even be overriden in the API call)
- the dedup system itself doesn't care of the parser's specificities:it's just checking if the hash_code of that new finding is the same or not as that other finding. 
Of course I'm supposing that the dedup will not work with one finding from a parser and another finding from another parser but I don't think this ever worked, did it?

**Comment by Maffooch** [comment]
@ptrovatelli It does work actually! I was as surprised as you are. In a real world scenario, it probably wouldn't work as the descriptions is part of the hashcode as well. Check out a [test](https://github.com/DefectDojo/django-DefectDojo/blob/dev/tests/dedupe_unit_test.py) I had written for deduplication. 

So the parser computes _a_ hashcode so that it can rule out duplicates from the same scan. Deduplication uses a standardized hash code found the Finding model. If dedupe were to use the parsers hash code, it would rarely work as most parsers kind of do their own things with hashcodes.

**Comment by ptrovatelli** [comment]
I didn't know there were 2 hash_code! so the one in the DB is the dedup one? couldn't we make this one configurable per parser?
there are for sure 2 families of parsers: the kind of ZAP working on endpoints, and the kind of sonar/checkmarx etc working on file_path which is file name + line number; 
I haven't looked at your code in details but last time I check, I did see some specificities in the dedup code to handle those different families of parsers. I don't think that we can ignore those specificities. 
My idea of a (dedup) hash_code configurable per parser would also enable to take into account these two families of parsers

**Comment by ptrovatelli** [comment]
and for dedup across different parsers, well it would obviously work if they have the same fields configured for dedup, and if those are filled the same way...

**Comment by wurstbrot** [comment]
For dependency check, from my point of view you take the library+CVE for a hash code as this is unique.

**Comment by ptrovatelli** [comment]
yes for dependency check it's easy to uniquely identify a vuln. 
For source code analysis it may be a bit tricky as the line number may be changing and still the vuln is the same as before and should be identified as duplicate. However we could get help from new fields from reports to work on duplicates.
For example checkmarx has already an advanced algo inside to track issues even in changing code (I'd hope so at least!). The reports include a "NodeId" which I is probably uniquely identifying a vuln location, independenly of the line number. I'll need a little bit of testing to make sure it does what I think.
Also there is another hicup: in defectDojo we make an aggregation on multiples findings from checkmarx and end up with less of them. This is what Maffooch was talking about regarding the first pass on deduplication inside the parser. For example in this unit test file multiple_findings.xml there are 3 findings from checkmarx, with 3 unique NodeId but we actually keep only two of them because we only look at "sink filename" + "sink line number", when checkmarx also look at "source filename" + "source line number". 
So it's not always easy but having a configurable hash_code per parser could answer most of these scenarii

**Comment by wurstbrot** [comment]
Your description highlights that it is parser related logic to specify a unique value (e.g. hash) to identify duplicates.

**Comment by valentijnscholten** [comment]
Deduplication without line numbers worked fine before #1395. I think #1395 should be reverted and reviewed/tested thoroughly before merging it back into dev. It breaks too many things that were working (or working more or less) before.

**Comment by ptrovatelli** [comment]
it's true that #1395 was merged a bit fast. abandonning both "skip_duplicates" and "close_old_findings" should have been discussed before merging as many ppl were probably relying on them. maybe we should revert, agree on the exact behavior and take the time to dev something that works for everyone? 
the migration part can probably be left though, to avoid adding another "rollback migration"

**Comment by Maffooch** [comment]
Ive been stewing on this a few days. I don't believe #1395 was merged too fast. The first PR was open for 6 days (closed due to wacky commits) and the second (#1395) was open for another week before being merged. Both of these PR's were exactly the same. 

Additionally, there was a [unit test](https://github.com/DefectDojo/django-DefectDojo/blob/dev/tests/dedupe_unit_test.py) written to ensure deduplication is working as _intended_. Admittedly, that one was merged quickly and most likely slid under the radar.

Discussion with both @devGregA  and @aaronweaver occurred throughout the entire process of  the PR. It "worked" in various places before when it should not have been. For example, hash code was being computed before endpoints were added. This equates to endpoints being out of the equation completely. Line numbers were totally considered originally. The issue was that line numbers that were None were treated as equal.  Static and dynamic attributes were often not assigned because of parser discrepancies. This is another reason endpoints were not being considered. Once all the changes were made to fix the intentions of deduplication, the APIv2 options were completely broken. There were just too many things that were not 100% and duplicate status was being handed out too easily. 

As mentioned in #1128, 'None' values create quite the problem with deduplication. A good point was made in that thread regarding whether parsers should handle the dedupe process. It will be a never ending battle of cleaning up after people who don't intimately understand deduplication, or don't bother at all. A central system is the best path to consistency. 

Also, just to explicitly clear this up, hashcode generated by parserers is **not** the hashcode used in dedupe. Hash code used in dedupe can be found in the compute_hash_code function in the Finding model. This is done so that deduplication can happen between different scanners.  

With all that being mentioned, I have a proposal to appease the masses. "skip_duplicates" and "close_old_findings" can be added back, and attempted to be corrected to work with the current dedupe implementation. If deduplication is enabled in settings, neither of those options will do anything and the unified deduplication process will take affect. if not enabled, those options will "work" as originally designed. This way everyone can be happy while still accomplishing both goals.

**Comment by valentijnscholten** [comment]
Maybe we should just accept that things break in the dev branch. On the other hand 6 days during a holiday period with no mention on slack does not really raise awareness.

Anyway, the important points for me were (are) the apiv2 options "skip_duplicates" and "close_old_findings". Both working correctly with findings without line numbers, which is common for third party dependency scanners.

A source of the problem could be that "as intended" might be different from person to person as long as it is not documented. I must admit also that have not looked at certain parts like static vs dynamic. Or endpoints. If the list of endpoints is part of the hash, might that not generate new findings when only a subset of endpoints gets fixes?

Maybe re-add the two apiv2 options and fix the line number thing and anything else should be new PRs and/or github issues?

**Comment by wurstbrot** [comment]
> Maybe we should just accept that things break in the dev branch.
Deduplication is broken in _master_/Production

**Comment by Maffooch** [comment]
The thing is that they weren't working according to the documentation. They used the same hashcode as the central dedupe. The changes were made to reflect that of the documentation. With regards to line numbers, @ptrovatelli gave an excellent example on why line numbers should be removed from this equation.

The has code is computed on each save of a finding. So it is not a one and done type of deal.

**Comment by Maffooch** [comment]
This has been in master the whole time? Well that changes things. #1395 has not reached the master branch yet. This makes my point even more important. Deduplication was very broken before my changes (and afterwards based on public opinion ;)). I assume @wurstbrot was using both the skip/close APIv2 combo and also tried the central dedupe as well.

**Comment by wurstbrot** [comment]
I better recheck...

**Comment by Maffooch** [comment]
Hmm. Im not familiar with that deployment. I can only guess its similar to kubernetes that uses master. How many login buttons do you have? The current master defaults to three.

**Comment by ptrovatelli** [comment]
I agree than 7 days may seem long when you push a commit and other commits may be merged, making yours conflicted :) Unfortunately we don't always have time to check all PR each day or even each week. Maybe a mention @ moderators in github or slack would be appreciated BEFORE starting on working on something that will bring breaking changes. And as discussed in a previous discussion about dedup a couple of months ago, we definitely need to agree on the dedup algorithm before coding it.
The only thing we have right now is the retro-documentation that I wrote in the readthedoc a couple of month ago (https://defectdojo.readthedocs.io/en/latest/features.html#deduplication), when dedup was broken for checkmarx and I was struggling to understand what was going on - that doc isn't valid anymore by the way.
Starting from here: 
- the line number bug definitely needs fixing
- re-adding skip_duplicate would be appreciated I guess. 
- close_old_findings available from global system settings may be enough? 
- what do you think of my proposal of a configurable hash_code per parser? 
  - we could even define families of parsers - about 3 I think for starters - 
  - parsers could be in families of parsers which define dedup/hash_code fields, or have their own set of fields to dedup on. 
  - for starters i think the model doesn't need to change but we'll probably need to add more fields.
    - for example a field with the source field of hash_code or debugging (the concatenated fields or whatever operation we apply on fields before hasing)
    - then some parsers will probably need additional fields. this could be handled by generic "generic_1, generic_2, generic_3" fields that would be used differently by parsers but would allow a single change in the model. 
  - the dedup would be generic and done outside of the parser, based on the configuration and the fields populated by the parser:  for example file_name, line_number, generic_1. 
  - the configuration would be modifiable in settings.py (with a reasonable default, base on families of parsers)

**Comment by Maffooch** [comment]
Will do that from now on. 

I think the first three bullets are good, but the fourth one really bothers me. If you're wanting to delegate dedupe to parsers, I have a feeling the amount of families will balloon with time. 

Going off your family idea, what if we made an import dedupe that filters all findings based on test type and only include items in hashcode that are not 'None'? It could be done in the import functions instead of parsers. There is already a field in Finding that records what scanner imported it (assuming it is actually used). This would cover most cases with in house scanners and we can rely on the system wide dedupe for cross scanner stuff. This would also include the functionality that skip_duplicates had as it could be enabled on a by import basis.

**Comment by ptrovatelli** [comment]
> If you're wanting to delegate dedupe to parsers, I have a feeling the amount of families will balloon with time.

@Maffooch nope, the fourth bullet reads "done OUTSIDE of the parser" :)
The only thing the parsers need to do is fill out findings fields. based on those fields and a global configuration, an outside process generates the hash_code and makes the dedup.

**Comment by Maffooch** [comment]
I guess give it a shot!

**Comment by madchap** [comment]
I [believe the issue I just opened](https://github.com/DefectDojo/django-DefectDojo/issues/1506) is the same. I am on dev commit `ad52191` and no more dedup on my "high-risk" semi-prod instance... :-/

**Comment by wurstbrot** [comment]
Just to mention, I am using re-import on my prod. instance for now.
