### ISSUE TITLE
Leave findings status untouched if re-uploading scan report

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1507]
**Is your feature request related to a problem? Please describe**
Upon re-uploading a scan report atop one that was originally imported (and triaged, analysed), the re-upload of the report marks inactive the ones that were previously marked active and got fixed (i.e. no longer show up in the scan report), and re-activate the ones that were manually marked as inactive.

This looks like a decent behavior I guess.

However, it would be nice that, for those findings that were actually worked on and set a specific status, that the re-upload does not override the status that was set -- at least not automatically.

**Describe the solution you'd like**
Maybe a checkbox to avoid a possible override at the test level?
Or using tag? i.e. if a specific tag is found on the finding, then do not override? (and offer some configuration there)

**Comment by ptrovatelli** [comment]
Hi @madchap . What statuses do you have in mind exactly? 
You can set a finding as "false positive" and this remains upon re-import. 
If you manually set a finding as inactive thinking you've fixed it, but when re-importing a report the vulnerability is still in the report, it means that your fix didn't work and to me it's normal that the finding be re-activated.

**Comment by madchap** [comment]
So let's say I've forked a library to fix some vulnerabilities. A scanner will pick up this fork as being the original, vulnerable library and raise a flag. Dojo will re-activate the finding on the 2nd round, so the analyst has to go back in a mark it inactive again. The same if my product has a whitelist of kind and forbids the use of a non-whitelisted, vulnerable methods in the library, which the scanner would pick up and re-activate.

However, your point is definitively valid too and I think the current default behavior is actually good.

That's why I was thinking of an override boolean -- i.e. "freeze", or "Manual override", or whatever. For those findings you're definitely sure should not be re-opened upon a new scan being imported, they should be left alone. The default behavior could remain the same as it is today.

What do you think?

**Comment by ptrovatelli** [comment]
why not although marking them as false positive would do the trick wouldn't it?

**Comment by madchap** [comment]
Yes, I would agree. The 2nd case if a bit tricky, because the vulnerable code is still in the library, albeit we just do not allow any calls to it for example. So it's not truly a false-positive so to speak.

Then, does having an "Active, False-positive" make any sense to you? It does not much to me.

**Comment by ptrovatelli** [comment]
right now active / false positive is not possible, the GUI forbids it. It reasonable normal to me.

by the way, regarding your first example I don't think that dependency check would pickup your forked library (I assume that's the scanner you have in mind)  because it recognizes vulnerable libs based on vendor, product, and version (see jeremylong.github.io/DependencyCheck/general/internals.html ) and you'd probably change the version when forking, maybe even the vendor

for the second example, false positive seems to apply to me. the dependencies scanners were never able to know whether the vulnerable code is called or not. if for any reason you know that the vulnerable code is not called (be it that you have checked all calls in your code or you have enforced a whitelist) then marking the vuln as false positive is the standard treatment. 
Although I'm not a fan of marking any lib vulnerability as false positive in general, and I advocate for leaving them active until the lib has been updated, just in case!
The problem if you mark it as false positive (or mark it inactive by any other mean after making defectDojo evolve): what if tomorrow there is another vuln found in this library, on a function that you have whitelisted? you'll never notice that this new vulnerability was found. 

To me the best thing to do is just leave a comment saying that it can be ignored and why; scan after scan you'll see this (active) vuln and ignore it; sometimes you'll check if your analysis is still valid. One day you'll take the time to update the dependency and then everyone's happy :)

**Comment by madchap** [comment]
> right now active / false positive is not possible, the GUI forbids it. It reasonable normal to me.
![image](https://user-images.githubusercontent.com/5468769/63703998-60d0f780-c82a-11e9-8b4b-581818b7e09b.png)

But not a scan re-upload apparently.

> by the way, regarding your first example I don't think that dependency check would pickup your forked library (I assume that's the scanner you have in mind) because it recognizes vulnerable libs based on vendor, product, and version (see jeremylong.github.io/DependencyCheck/general/internals.html ) and you'd probably change the version when forking, maybe even the vendor
I don't think I have mentioned "dependency check" (the tool) anywhere?

> for the second example, false positive seems to apply to me. the dependencies scanners were never able to know whether the vulnerable code is called or not. if for any reason you know that the vulnerable code is not called (be it that you have checked all calls in your code or you have enforced a whitelist) then marking the vuln as false positive is the standard treatment.
It depends on your customer. I have one that is not satisfied with this answer. If the code is still there, it could eventually get called one way or another that you had not planned. E.g. a software bug.

> Although I'm not a fan of marking any lib vulnerability as false positive in general, and I advocate for leaving them active until the lib has been updated, just in case!
True.

> The problem if you mark it as false positive (or mark it inactive by any other mean after making defectDojo evolve): what if tomorrow there is another vuln (of the same type) found in this library, on a function that you have whitelisted? you'll never notice that this new vulnerability was found.

> To me the best thing to do is just leave a comment saying that it can be ignored and why; scan after scan you'll see this (active) vuln and ignore it; sometimes you'll check if your analysis is still valid. One day you'll take the time to update the dependency and then everyone's happy :)
Yes, doing that already ;-)
