### ISSUE TITLE
change the name of defect dojo

### ISSUE THREAD

**Issue by randiee** [DefectDojo/django-DefectDojo#1569]
It's cringey and embarrassing for such a solid project.  I don't know who thought it was a good idea, but they shouldnt be allowed to name things.  It sounds like a discount martial arts dojo you'd find in a strip mall.  When we tell higher ups the name of our vulnerability management solution, we see them cringe at the name.

**Comment by Timmy-Swimmy779** [comment]
You're cringey and embarrassing you middle-aged neckbeard. I don't know who thought it was a good idea to CONCEIVE you but they shouldn't have been allowed to name you. Randiee sounds like what would happen if you did a marathon. He ran then he died. It is good though that you came across Defect Dojo. You should test it on yourself because I'm pretty sure you're defective.
But that is beside the point, did you have any ideas for a different name?

-Timmy Swimmy

**Comment by devGregA** [comment]
.... I created it. I named it. OWASP Code of Ethics: https://www.owasp.org/index.php/About_The_Open_Web_Application_Security_Project

Please everyone, be nice to everyone. Thanks.
