### ISSUE TITLE
Dependency check CWE not parsed correctly

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1610]
**Bug description**
It appears the default 1035 CWE is always taken as a fallback when importing a dependency check report (recent ones).

It seems that line 25 of the parser would treat CWE as a single field, whereas now, there could be several per a 5.1.1 dependency check output?

```
<vulnerability source="NVD">
          <name>CVE-2012-5882</name>
          <severity>MEDIUM</severity>
          <cvssV2>
            <score>4.3</score>
            <accessVector>NETWORK</accessVector>
            <accessComplexity>MEDIUM</accessComplexity>
            <authenticationr>NONE</authenticationr>
            <confidentialImpact>NONE</confidentialImpact>
            <integrityImpact>NONE</integrityImpact>
            <availabilityImpact>NONE</availabilityImpact>
            <severity>MEDIUM</severity>
          </cvssV2>
          <cwes>
            <cwe>CWE-79</cwe>
          </cwes>
          <description>Cross-site scripting (XSS) vulnerability in the Flash component infrastructure in YUI 2.5.0 through 2.9.0 allows remote attackers to inject arbitrary web script or HTML via vectors related to uploader.swf, a similar issue to CVE-2010-4208.</description>
          <references>
            <reference>
[... truncated ... ]
```

**Comment by ptrovatelli** [comment]
Hi Madchap,
I saw the same issue with sonar scanner: there is sometimes several cwe. currently we take only the first one. 
The problem is that cwe is an integer in the model right now so it can't hold several values without changing the model which will affect all the scanners; we could add a new field though;
- either varchar and holds all the cwe
- or something like it's done for the endpoints with two more tables dojo_endpoint, dojo_finding_endpoint

**Comment by jvz** [comment]
You could use a foreign key to the CWE table. Or add an array field (only for postgres, though).
