### ISSUE TITLE
Deduplication does not work for NPM Audit Scan

### ISSUE THREAD

**Issue by AndreyMZ** [DefectDojo/django-DefectDojo#1640]
**Bug description**

Deduplication does not work at least for NPM Audit Scan.

**Steps to reproduce**
1. Run DefectDojo with [Docker Compose](https://github.com/DefectDojo/django-DefectDojo/blob/master/DOCKER.md)
2. Switch on deduplication:
	1. Go to *System Settings* 
	2. Switch on *Deduplicate findings*
	3. Click *Submit*
3. Add a product:
	1. Go to *Add Product*
	2. Fill required fields.
	3. Click *Submit*
4. Add a new engagement:
	1. Go to *Add New CI/CD Engagement*
	2. Ensure that *Deduplication on engagement* is switched off.
	3. Click *Import Scan Results*
	4. Set *Scan type* to *NPM Audit Scan*
	5. Set *Choose report file* to e.g. npm-audit.json (see the sample below)
	6. Click *Upload File*
5. Add another engagement with the same scan results.

**Actual behavior**
All findings have status just "Inactive".

**Expected behavior**

All findings have status "Duplicate".

**Deployment method** 
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Windows 10 
 - DefectDojo Commit Message: 42f1d4e7: Update issue templates [2019-10-02 16:01:25 -0500]

**Sample scan files** 

[npm-audit.json.txt](https://github.com/DefectDojo/django-DefectDojo/files/3824517/npm-audit.json.txt)

**Comment by ptrovatelli** [comment]
Hello @AndreyMZ ,
I have been working on making deduplication work for all the scanners by making it configurable for each scanner. Feel free to try out this PR: 
https://github.com/DefectDojo/django-DefectDojo/pull/1540

I have just commited the configuration for npm audit scan. I was able to deduplicate the provided file. 

There was another adjustment in the hash_code computation : it was computed only if: 
- finding is static and there is a file_path
- or finding is dynamic and there are endpoints

The scanner marks findings as dynamic and they don't have endpoints. 
This is more an error in the scanner because the findings should be marked static instead
However, it doesn't have a file_path either so it wouldn't have solved it either! 
Anyways, I have completely removed this condition: now we always compute the hash_code, I see no reason to make that kind of assumptions

I have made the deduplication based on: title + severity. 
That will work in most case, except when the title changes in the tool due to an evolution in npm tooling.
Ideally, I'd say the scanner should import the library name into file_path
Then we could deduplicate based on "cwe + file_path + severity " which will be more robust to tool update and would also makes it possible to find duplicates across different scanners as it doesn't include any scanner-specific information (title)

Also they should be marked as static (although we don't really care for the deduplication)

To try the PR: 
Don't use on a production environment because you may have issues with django db migration later, if another PR is merged before this one. You should wait for the PR to be merged to start using it on production environment
Try on a fresh environment, without any populated database (again to avoid issues with django db migrations)
```
# this will remove any data from the database if there is any!
docker-compose down --volumes
git fetch origin pull/1540/head:pr-1540
git checkout pr-1540
docker-compose build
docker-compose up
```

**Comment by AndreyMZ** [comment]
Thank you! Waiting for the PR to be merged.

**Comment by ptrovatelli** [comment]
Hello @AndreyMZ ,
Can you confirm that this is fixed on the latest dev now that https://github.com/DefectDojo/django-DefectDojo/pull/1665 was merged? At least when importing npm audit as such with scan type "NPM audit scan"? 
There is this other issue open https://github.com/DefectDojo/django-DefectDojo/issues/1692 regarding generic findings. 

Thanks!

**Comment by AndreyMZ** [comment]
Hello,
Yes, this is fixed in `dev` branch. Thank you.
