### ISSUE TITLE
Tests finding counts at 0

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1653]
**Bug description**
All counters at 0 when viewing an engagement's page, under "Tests".

![image](https://user-images.githubusercontent.com/5468769/68906445-8fcd7a00-0744-11ea-83e6-6a6fb0700330.png)

`dev` on v. 1.5.4 ( 70e29801 )

**Comment by ptrovatelli** [comment]
Hi @madchap . I have found a couple of issues on that engagement page (see https://github.com/DefectDojo/django-DefectDojo/issues/1643 )
Can you check if your issue was already there at https://github.com/DefectDojo/django-DefectDojo/commit/e49bbb5e4fb8cab0d8e2214f153744ed86a8d39a ? If not, your problem might come from  https://github.com/DefectDojo/django-DefectDojo/commit/1720c95bf831236b81c5713d6006b29e55dec33c too.

**Comment by madchap** [comment]
Yep, I see, I thought of that when I saw them passing by. I'll take a look whenever, this one is not so critical I guess.

Thanks @ptrovatelli !

**Comment by madchap** [comment]
OK, so tracked it down to `view_eng.html` at line 196, calling `display_tags.py` line 677. Effectively, using Active=True, Verified=True. That's just another place to change to adapt to Verified=False, as started.
