### ISSUE TITLE
All fortify issues are not reflecting in DefectDojo

### ISSUE THREAD

**Issue by amrityam** [DefectDojo/django-DefectDojo#1657]
**Bug description**
I am uploading the XML report exported from Fortify SCA 19.10 and 17.20 to DefectDojo. Instead of showing all the vulnerabilities from each category,  DefectDojo is showing one vulnerability from each category.

**Steps to reproduce**
1.For a product navigate to Findings tab and click on import scan results.
2.Fill up the required details and choose scan type as Fortify Scan and upload the xml file generated by fortify
3.After successful upload, one can see DefectDojo is showing one vulnerability from each fortify  scan category instead of showing all vulnerabilities from all category.

XML was generated by using below command.
ReportGenerator -format XML -template "DefaultReportDefinition.xml" -f "C:\Demo\SourceCode\WebGoat-Legacy\WebGoat_Fortify_DefaultReportDefinition.xml" -source  "C:\Demo\SourceCode\WebGoat-Legacy\webgoat6-cli.fpr"

Please note for other -template types like DeveloperWorkbook.xml or OWASP2013.xml , while uploading the xml files in DefectDojo, Server Error (500) is coming. 

**Expected behavior**
DefectDojo must show all the fortify reported vulnerabilites.

**Deployment method** *(select with an `X`)*
- [x] Docker

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
[files.zip](https://github.com/DefectDojo/django-DefectDojo/files/3854428/files.zip)

**Sample scan files** (optional)
Attached

**Comment by ptrovatelli** [comment]
Hello @amrityam . 
It seems that this parser was done for that "defaultReportDefinition" report which doesn't have all the details. 
The structure is quite strange actually: it gives counts for a given type of vulnerability and then gives a couple of random files concerned, but not all: 
```
                    <GroupingSection count="4">
                        <groupTitle>Command Injection</groupTitle>

(...)
                        <Issue iid="2390CF7C0D738E2BE2F968716E8C1539" ruleID="1C7A212C-7723-452B-97D5-4D94EC85829E">
                            <Category>Command Injection</Category>

(...)
                            <Primary>
                                <FileName>WSDLScanning.java</FileName>
                                <FilePath>src/main/java/org/owasp/webgoat/lessons/WSDLScanning.java</FilePath>
(...)
                            </Primary>
                            <Source>
                            <FileName>ParameterParser.java</FileName>
```

When in the developer workbook report we can see that not only WSDLScanning.java is touched but also Exec.java:
                        <Issue iid="C9089B27AAADAC7A563B70C8BFE1F84C" ruleID="544B7340-C058-4FF7-833C-62932AAFA34A">
                            <Category>Command Injection</Category>
(...)
                            <Primary>
                                <FileName>WSDLScanning.java</FileName>
                                <FilePath>src/main/java/org/owasp/webgoat/lessons/WSDLScanning.java</FilePath>


```
                        <Issue iid="1EE43C8EBD079E2A1595DC2E202F0C99" ruleID="5760613C-9AF8-41EF-8431-66B6FBD4717A">
                            <Category>Command Injection</Category>
(...)
                            <Primary>
                                <FileName>Exec.java</FileName>

```
For more details, I think we should adapt the parser for those other formats and also get at least detailed information for each filename :
What is does now is aggregate vulns on title + sev + cwe_id, ignoring the file name, and then putting the last filename found in the category into "file_path"
The filename should be part of the aggregation so that we have at least one finding for each filename. 
Still we wouldn't have all the findings because there might be sometimes several of the same type in the same file (at different line number) but I think this is a good compromise
To go further, we could also count the number of occurences so that one can verify that all the vuln are here. The field nb_occurences was added in that PR https://github.com/DefectDojo/django-DefectDojo/pull/1540 and will be merged to dev soon hopefully. 

The fortify code is here: dojo/tools/fortify/parser.py is someone feels like it :)

**Comment by amrityam** [comment]
@ptrovatelli , yes we should track all the occurrences of the vulnerabilities reported by Fortify.Hope this will be fixed soon.

**Comment by amrityam** [comment]
@ptrovatelli And DeveloperWorkbook.xml gives more detail information like source to sink.It should be supported by DefectDojo.

**Comment by ptrovatelli** [comment]
there are also new fields for source/sink information in that PR #1540 . What was done on checkmarx scanner could be applied to fortify as well: two scanners
- one aggregated on type of vuln/ file_path
- one detailed with source/sink detailed information

**Comment by dougmcdorman** [comment]
My notes on creating a Fortify XML report might be useful as well.
#### Creating Fortify XML Reports for Import to Defect Dojo

A Fortify XML file is created from the fortify .fpr file

Note a .fpr file is a .zip file with a collection of files in it.

The reportgenerator utility can be used to generate an XML file from the FPR file:

```C:\Program Files\HPE_Security\Fortify_SCA_and_Apps_17.20\bin\ReportGenerator.bat -format XML -f fortify_v18.20.1046.xml -source fortify_v18.20.1046.fpr```

The above method will get you just one representative issue from each type of issue (&lt;GroupingSection&gt;) .
In order to import all issues you need to jump through a couple of hoops 

```cd %FORTIFY_HOME%/Core/config/reports```

Copy the DefaultReportDefinition.xml to DefaultReportDefinitionAllIssues.xml

Change

```<IssueListing limit="1" listing="true">```

To:

```<IssueListing limit="-1" listing="true">```

  
Change:

```<Refinement>[fortify priority order]:critical OR [fortify priority order]:high</Refinement>```

To:

```<Refinement/>```

The reportgenerator utility can be used to generate an XML file from the FPR file, specifying the new template file:

```C:\Program Files\HPE_Security\Fortify_SCA_and_Apps_17.20\bin\ReportGenerator.bat -template DefaultReportDefinitionAllIssues.xml -format XML -f fortify_v18.20.1046.xml -source fortify_v18.20.1046.fpr```

**Comment by dougmcdorman** [comment]
Also note that there are templates in the %FORTIFY_HOME%/Core/config/reports directory that make the reports quite different. The sections / headings have different names so the parser would not recognize the sections.

**Comment by dougmcdorman** [comment]
Also I don't know if Fortify will mark items in the report as false positive. I am pretty sure the parser would not notice if it did. I know that checkmarx does include in the XML report if the issue has been marked as false positive but the parser doesn't notice.

**Comment by ptrovatelli** [comment]
> I know that checkmarx does include in the XML report if the issue has been marked as false positive but the parser doesn't notice.

haha exactly! noticed that a couple of days ago; will commit the fix in the next few days for checkmarx because I didn't find a way to exclude false positive when exporting with checkmarx plugin for jenkins.

**Comment by Apipia** [comment]
Just want to add to this. 
First off thanks @dougmcdorman for the post and the notes. Helped me out a lot. (limit=-1, genius)
Secondly I wanted to _suggest_ a change to the fortify parser and the data as it's displayed in Defect Dojo. Rather than having each **groupTitle** as a single Finding with a collection of horribly formatted LineStarts and FileNames in the description, we create a single Finding for each issue (as redundant as that may feel) given that a finding in DefectDojo has a _single_ file name and line number associated with it.

Is that something other Fortify users would like to see?

**Comment by dougmcdorman** [comment]
> haha exactly! noticed that a couple of days ago; will commit the fix in the next few days for checkmarx because I didn't find a way to exclude false positive when exporting with checkmarx plugin for jenkins.

Sorry, off topic for this issue. But as far as I can tell the Checkmarx API does not allow you to exclude false positives either. You can do it in GUI but that doesn't help in this case. Hopefully Checkmarx will fix that someday but I won't hold my breath.

**Comment by madchap** [comment]
@amrityam would you know if PR https://github.com/DefectDojo/django-DefectDojo/pull/1706 would help your cause?
