### ISSUE TITLE
Deduplication does not work for API

### ISSUE THREAD

**Issue by AndreyMZ** [DefectDojo/django-DefectDojo#1692]
## Bug description
Deduplication does not work when findings are created one by one via APIv2.

## Steps to reproduce
1. Go to `/system_settings` and switch on *Deduplicate findings*.
2. Go to `/product/add` and add a *Product* (with ID `1`).
3. Go to `/test_type/add` and register a new *Test type* with name `My Scan` (with ID `165`).
4. Go to `/product/1/new_engagement/cicd` and add a new *CI/CD engagement* (with ID `1`).
5. Go to `/engagement/1/add_tests` and add a new *Test* with *Test type* `My Scan` (with ID `1`).
6. Go to `/api/v2/doc/`
7. Authorize.
8. Create a finding via API:
	1. Go to findings > POST /api/v2/findings/
	2. Set data to the following:
	
		~~~json
		{
			"test": 1,
			"found_by": [165],

			"active": true,
			"verified": true,
			"duplicate": false,
			"false_p": false,
			
			"title": "Example title",
			"cwe": 346,
			"cve": "CVE-2018-14732",
			"severity": "High",
			"numerical_severity": "S1",
			"description": "Example description.",
			"mitigation": "Example mitigation.",
			"impact": "Example impact.",
			"references": "Example references.",
			
			"hash": "6cbb5d2dcb11610a99eb3f633dc246690c0acf33327bf7534f95542caa8f27c4",
			"unique_id_from_tool": "6cbb5d2dcb11610a99eb3f633dc246690c0acf33327bf7534f95542caa8f27c4"
		}
		~~~
	
	3. Click *Try it out!*
9. Create the same finding again.
	1. Click *Try it out!* again.

## Actual result
Two findings. No duplicates.
(According to the logs deduplication was run, but did not find any duplicates.)

## Expected result
The second finding is a duplicate of the first one.

## Deployment method
*(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

## Environment information
Operating System: CentOS Linux release 8.0.1905 (Core)
DefectDojo Commit Message: `e55e51ed: Merge pull request #1688 from Aniket21mathur/Fix [2019-12-08 20:28:47 +0530]` (branch: `dev`)

## Console logs
(After setting `'level': 'DEBUG'` for the `dojo.specific-loggers.deduplication` logger in `dojo/settings/settings.dist.py`.)
~~~
uwsgi_1         | Saving finding of id None
uwsgi_1         | No configuration for hash_code computation found; using default fields for dynamic scanners
uwsgi_1         | computing hash_code for finding id 9 for scan_type My Scan based on: title, cwe, line, file_path, description, endpoints
uwsgi_1         | title : Example title
uwsgi_1         | cwe : 346
uwsgi_1         | line : None
uwsgi_1         | file_path : None
uwsgi_1         | description : Example description.
uwsgi_1         | compute_hash_code - fields_to_hash = Example title346NoneNoneExample description.
uwsgi_1         | applying rules
rabbitmq_1      | 2019-12-11 08:31:01.272 [info] <0.539.0> accepting AMQP connection <0.539.0> (172.19.0.6:39212 -> 172.19.0.2:5672)
uwsgi_1         | Start from server, version: 0.9, properties: {'information': 'Licensed under the MPL.  See https://www.rabbitmq.com/', 'product': 'RabbitMQ', 'copyright': 'Copyright (C) 2007-2019 Pivotal Software, Inc.', 'version': '3.7.17', 'capabilities': {'direct_reply_to': True, 'exchange_exchange_bindings': True, 'per_consumer_qos': True, 'consumer_priorities': True, 'consumer_cancel_notify': True, 'authentication_failure_close': True, 'connection.blocked': True, 'basic.nack': True, 'publisher_confirms': True}, 'platform': 'Erlang/OTP 22.0.7', 'cluster_name': 'rabbit@76d5d6eaed99'}, mechanisms: [b'AMQPLAIN', b'PLAIN'], locales: ['en_US']
rabbitmq_1      | 2019-12-11 08:31:01.276 [info] <0.539.0> connection <0.539.0> (172.19.0.6:39212 -> 172.19.0.2:5672): user 'guest' authenticated and granted access to vhost '/'
uwsgi_1         | using channel_id: 1
uwsgi_1         | Channel open
celeryworker_1  | [2019-12-11 08:31:01,302: INFO/MainProcess] Received task: async_dedupe[99c83804-d863-47b0-80ad-70c543de988d]
celeryworker_1  | running deduplication
celeryworker_1  | sync_dedupe for: 9:Example title
celeryworker_1  | scan_type for this finding is :My Scan
celeryworker_1  | deduplication algorithm: legacy
nginx_1         | 10.51.1.62 - - [11/Dec/2019:08:31:01 +0000] "POST /api/v2/findings/ HTTP/1.1" 201 1380 "http://10.52.149.139:8080/api/v2/doc/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.99 Safari/537.36 Vivaldi/2.9.1705.41" "-"
celeryworker_1  | Found 0 findings with same cwe, 0 findings with same title: 0 findings with either same title or same cwe
celeryworker_1  | [2019-12-11 08:31:01,326: INFO/MainProcess] Task async_dedupe[99c83804-d863-47b0-80ad-70c543de988d] succeeded in 0.023522516014054418s: None
uwsgi_1         | [pid: 1|app: 0|req: 176/181] 10.51.1.62 () {54 vars in 1107 bytes} [Wed Dec 11 08:31:00 2019] POST /api/v2/findings/ => generated 1380 bytes in 512 msecs (HTTP/1.1 201) 5 headers in 156 bytes (1 switches on core 1)
celeryworker_1  | [2019-12-11 08:31:01,496: INFO/MainProcess] Received task: dojo.tasks.async_dupe_delete[5e9b2e73-780e-4926-890b-954e71b0a053]
celeryworker_1  | [2019-12-11 08:31:01,497: INFO/MainProcess] dojo.tasks.async_dupe_delete[5e9b2e73-780e-4926-890b-954e71b0a053]: delete excess duplicates
celeryworker_1  | [2019-12-11 08:31:01,502: INFO/MainProcess] Task dojo.tasks.async_dupe_delete[5e9b2e73-780e-4926-890b-954e71b0a053] succeeded in 0.004714707960374653s: None
uwsgi_1         | Saving finding of id None
uwsgi_1         | No configuration for hash_code computation found; using default fields for dynamic scanners
uwsgi_1         | computing hash_code for finding id 10 for scan_type My Scan based on: title, cwe, line, file_path, description, endpoints
uwsgi_1         | title : Example title
uwsgi_1         | cwe : 346
uwsgi_1         | line : None
uwsgi_1         | file_path : None
uwsgi_1         | description : Example description.
uwsgi_1         | compute_hash_code - fields_to_hash = Example title346NoneNoneExample description.
uwsgi_1         | applying rules
celeryworker_1  | [2019-12-11 08:31:12,484: INFO/MainProcess] Received task: async_dedupe[af56b32b-5ba4-43cc-83cf-b0bf94b2a78f]
celeryworker_1  | running deduplication
celeryworker_1  | sync_dedupe for: 10:Example title
celeryworker_1  | scan_type for this finding is :My Scan
celeryworker_1  | deduplication algorithm: legacy
celeryworker_1  | Found 1 findings with same cwe, 1 findings with same title: 1 findings with either same title or same cwe
nginx_1         | 10.51.1.62 - - [11/Dec/2019:08:31:12 +0000] "POST /api/v2/findings/ HTTP/1.1" 201 1381 "http://10.52.149.139:8080/api/v2/doc/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.99 Safari/537.36 Vivaldi/2.9.1705.41" "-"
uwsgi_1         | [pid: 1|app: 0|req: 177/182] 10.51.1.62 () {54 vars in 1107 bytes} [Wed Dec 11 08:31:12 2019] POST /api/v2/findings/ => generated 1381 bytes in 342 msecs (HTTP/1.1 201) 5 headers in 156 bytes (1 switches on core 0)
celeryworker_1  | no endpoints on one of the findings and the new finding is either dynamic or doesn't have a file_path; Deduplication will not occur
celeryworker_1  | deduplication flags for new finding 10 and existing finding 9 flag_endpoints: False flag_line_path:False flag_hash:True
celeryworker_1  | [2019-12-11 08:31:12,532: INFO/MainProcess] Task async_dedupe[af56b32b-5ba4-43cc-83cf-b0bf94b2a78f] succeeded in 0.04748704598750919s: None
~~~

**Comment by ptrovatelli** [comment]
Hi @AndreyMZ ; this is the historical behavior of the deduplication for manual findings I believe. Can you confirm that this is not a new problem that used to work before?  (we have recently merged an evolution on deduplication). the deduplication doesn't occur because your finding is marked as dynamic and doesn't have endpoints. 

I haven't tested on manual findings but the deduplication configuration should work fine.
According to the logs, your scan type is "My Scan"; did you choose that somewhere? 
If you coherently always create scan types named "My Scan", you can configure this scan type to deduplicate based on cwe + severity for exemple (although it's strange that you don't have a file_path or any endpoints and you will end up with a lot of duplicates in a real project) : in settings.dist.py: 

```
HASHCODE_FIELDS_PER_SCANNER = {
(...)    'My Scan': ['cwe', 'severity'],
}
```

```
HASHCODE_ALLOWS_NULL_CWE = {
(...)
    'My Scan': False
}
```


```
DEDUPLICATION_ALGORITHM_PER_PARSER = {
(...)
    'My Scan': DEDUPE_ALGO_HASH_CODE,
```

Can you try this?

**Comment by AndreyMZ** [comment]
> Can you confirm that this is not a new problem that used to work before? (we have recently merged an evolution on deduplication)

Yes, I confirm this. The logs also show this:
~~~
celeryworker_1  | deduplication algorithm: legacy
~~~


> the deduplication doesn't occur because your finding is marked as dynamic and doesn't have endpoints.

No, it is neither dynamic or static. I could mark it as static, but this does not help.


> it's strange that you don't have a file_path or any endpoints and you will end up with a lot of duplicates in a real project

It is not strange. The real examples of such test (scan) types are: [npm audit](https://docs.npmjs.com/cli/audit), [yarn audit](https://yarnpkg.com/lang/en/docs/cli/audit/), [symfony check:security](https://symfony.com/doc/current/setup.html#checking-security-vulnerabilities).

I will not end up with a lot of duplicates if the deduplication will work based on `unique_id_from_tool` or `hash_code`. When I use API, I can generate this fields correctly for each specific test type. This fields were added exactly for this purpose, weren't they?


> If you coherently always create scan types named "My Scan", you can configure this scan type to deduplicate based on <...> in settings.dist.py <...>

No, I don't. I am going to add more test types as needed. And I do not want to change sources of DefectDojo every time I add a new test type. So, changing `settings.dist.py` is not an option. I hope, deduplication will work out of the box for any test type.

**Comment by ptrovatelli** [comment]
> It is not strange. The real examples of such test (scan) types are: [npm audit](https://docs.npmjs.com/cli/audit), [yarn audit](https://yarnpkg.com/lang/en/docs/cli/audit/), [symfony check:security](https://symfony.com/doc/current/setup.html#checking-security-vulnerabilities).

if npm audit and yarn audit scanners don't provide the library name, maybe they ought to be fixed in order to record this important information into `file_path` :)

> When I use API, I can generate this fields correctly for each specific test type. 

I don't follow here. what's your process for generating this kind of payload? are you manually (or with a scripting of yours) building this payload with some information that's coming from for example npm scan into this "My scan" scan type and filling yourself stuff as the unique_id_from_tool? Maybe I missed a usecase, that's not the way I usually do. I just import security reports

> This fields were added exactly for this purpose, weren't they?

Yes but the system was made to be as flexible as possible thanks to the configuration because there's a lot of scanners out there and it's hard to comply with all of them.

The algorighm that tried to match all the needs is the "legacy" one that I have left as is for the most part. I believe in a more simple way of doing things based on the configuration for each parser that will work for most people and that can still be finely tuned when required.

There is however a configuration step required to match the need of each tool. I  have started this configuration just for the tools I personnaly use and a couple more. However last time I checked npm scanner (here dojo\tools\npm_audit\parser.py)  didn't provide unique_id_from_tool so I have configured it to dedup based on 'title', 'severity'

> No, I don't. I am going to add more test types as needed. And I do not want to change sources of DefectDojo every time I add a new test type. So, changing `settings.dist.py` is not an option. I hope, deduplication will work out of the box for any test type.

It's not really source code, it's a configuration file.
If you're importing an NPM scan, you should choose the appropriate scan type and configure it in settings.dist.py. Then you can push that so that everyone else won't have to do the same. 
However this requires that you use the "normal" npm audit scanner. If everyone builds their own payload for each scanner then we cannot share configurations and we're back to trying to build a very clever algorithm that will match all the needs. That didn't work out so well thus far :)

**Comment by ptrovatelli** [comment]
Hello @AndreyMZ,
did any of the bypass worked for you? can you confirm my understanding of your use case? to sum it up: 

- if you're injecting customized fields then the configurable deduplication should match your needs but you need to configure yourself what you want to deduplicate on for each type of payload you use because we weren't able to produce an algorithm that just always works
- if you're injecting standard security reports, then the deduplication configuration is a one-time job that will work for everyone; still needs to be done once for each scanner

**Comment by ptrovatelli** [comment]
it's still possible to amend the default  "legacy" algorithm too. we could add conditions like "if unique_id_from_tool is present, deduplicate based on that". feel free to create a PR that fits your needs, we'll be glad to merge any sensible change :)
it's here https://github.com/DefectDojo/django-DefectDojo/blob/dev/dojo/utils.py function deduplicate_legacy

**Comment by AndreyMZ** [comment]
Stale bot, get lost.

**Comment by AndreyMZ** [comment]
Stale bot, get lost.

**Comment by valentijnscholten** [comment]
logs: ` no endpoints on one of the findings and the new finding is either dynamic or doesn't have a file_path; Deduplication will not occur`
this is the behaviour of the legacy dedupe algorithm which is trying to be smart about static vs dynamic findings, but doesn't get it right all the time. I do think any static scanner should set the file_path (and/or component name) otherwise DD has incomplete data.

**Comment by devGregA** [comment]
I believe we are good to close this per Valentijn's comment. Please re-open if I am incorrect.
