### ISSUE TITLE
Limit SSO logins to invited emails/whitelist only

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1697]
**Is your feature request related to a problem? Please describe**
Taking my own example, I am using the Google SAML login functionality, which works well (when it does not add crazy suffixes?)

However, anyone part of the organization can just click on "login with Google" and will automatically get "Staff" status, which is quite dangerous for the confidentiality of the information residing within dojo.

Ideally, a person should be able to "login with Google" (or else), only if that email is on a whitelist or a pending invitation list.

**Describe the solution you'd like**
No idea right now.

**Describe alternatives you've considered**
Go back to local login and forget about SSO :-/

**Additional context**
Add any other context, screenshots, sketch, code snippet, etc. about the feature request here.

**Comment by madchap** [comment]
@devGregA since you committed the initial feature, maybe you'd have an idea on top of your head?

**Comment by Maffooch** [comment]
I would think all that should be handled by the SSO provider (in your case Google). The SSO simply responds with a yes/no about whether the user will have access or not.

**Comment by madchap** [comment]
Right.

Well, I guess the simple #1711 goes a long way to make sure people don't see what they don't need to see.

I am actually going to close this for now and see if the need creeps back in later.

Cheers.

**Comment by arkwrn** [comment]
Hi @madchap , if i'm not mistaken to understand what you want , here's some step you can use :

1.  set `user.is_staff = False` in **dojo/pipeline.py**
2. Add following variables in Your **settings.py** :
```
SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS = ['company.com', 'example.com']
SOCIAL_AUTH_LOGIN_ERROR_URL = '/login'
SOCIAL_AUTH_BACKEND_ERROR_URL = '/login'
```
3. Thus all who have an email that is whitelist will be able to log in and only limited to active, need admin or owner permission to change the status from active to staff / admin because it must be changed from the admin panel manually.

I implemented it in my place so that everyone with our company email addresses can see the latest status in the dojo, but some people with special needs such as pentesters who want to rise to staff, they must send an approval email to me, so I can change his user into staff if deemed necessary .

Hope that helps you.

**Comment by madchap** [comment]
Hi @arkwrn,

> 1. set `user.is_staff = False` in **dojo/pipeline.py**

Indeed, I actually submitted a PR so that this becomes the default behavior.

> 2. Add following variables in Your **settings.py** :
> 
> ```
> SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS = ['company.com', 'example.com']
> SOCIAL_AUTH_LOGIN_ERROR_URL = '/login'
> SOCIAL_AUTH_BACKEND_ERROR_URL = '/login'
> ```

My idea was to restrict actual emails, not domains.

That being said, you pointed me to the doc that actually answers my question: https://python-social-auth.readthedocs.io/en/latest/configuration/settings.html#whitelists

So the email whitelisting is actually there too.
```
SOCIAL_AUTH_<BACKEND_NAME>_WHITELISTED_EMAILS = ['me@foo.com', 'you@bar.com']
Supply a list of email addresses to be white-listed. Any user with an email address in this list will login successfully, otherwise AuthForbidden is raised.
```

Cheers!

**Comment by arkwrn** [comment]
hi @madchap , nice to know that it can help 👍

**Comment by nareshbogathi** [comment]
Hi @madchap @arkwrn 

I am planning to use SAML2 for Defectdojo SSO with Yaml, Can you please help me to share some example code?
i am using like this, but it's failing in helm deployment
`extraConfigs:
  DD_SAML2_ENABLED: 'true'
  # If the metadata can be accessed from a url, try the
  DD_SAML2_METADATA_AUTO_CONF_URL: ${{ parameters.SAML2MetadataURL }}
  # Otherwise, downlaod a copy of the metadata into an xml file, and
  # list the path in DD_SAML2_METADATA_LOCAL_FILE_PATH
  # DD_SAML2_METADATA_LOCAL_FILE_PATH: '/path/to/your/metadata.xml'

  DD_SAML2_ATTRIBUTES_MAP: { Email: email, Username: launcher_id, Firstname: first_name, Lastname: last_name }`
  
  It's giving validation error
