### ISSUE TITLE
Improve efficiency of parser lookup

### ISSUE THREAD

**Issue by sergray** [DefectDojo/django-DefectDojo#1719]
`import_parser_factory` in [dojo/tools/factory.py](https://github.com/DefectDojo/django-DefectDojo/blob/dev/dojo/tools/factory.py#L76) uses the long list of conditional expressions to determine the right parser for the given `scan_type`, which has `O(N)` complexity, where `N` is the number of scan types (about 70 at the moment).

I would like to propose to create a lookup table (dictionary),  where `scan_type` is a key and a parser class is the value. 

That will require normalization of some parser interfaces, because some parsers are determined by file name (e.g. [Nessus](https://github.com/DefectDojo/django-DefectDojo/blob/dev/dojo/tools/factory.py#L81)), but this is easy to solve with a parser specific factory.

Also calls to the parsers vary, e.g. some parsers do not require file, but others may require `active` or `verified` parameter. This problem is easy to solve using `requires_file` and `handles_active_verified_statuses` functions in [dojo/tools/__init__.py](https://github.com/DefectDojo/django-DefectDojo/blob/dev/dojo/tools/__init__.py).

I also considered alternative of implementing a base parser class with automatic registration in a register of parsers, but rejected it as more complicated solution.

**Comment by Maffooch** [comment]
This is a cool idea! I dont think this is a major bottleneck though as its only 70 scanners. Maybe instead of a map, contributors could name their parser functions very similar to that of the fixture. This way, the scan type from the request can be used and doctored to represent a function name (such as adding underscores, or whatever), and then called with proper args. This would avoid all the checks while saving heap space.

**Comment by valentijnscholten** [comment]
dictionairy would be faster yes, but as long as we have lots of very ineffecient database query related stuff I think we should focus on that first.
