### ISSUE TITLE
Attach findings to multiple products (many-many relation)

### ISSUE THREAD

**Issue by anakin1** [DefectDojo/django-DefectDojo#185]
Sometimes I have findings that impact multiple products - e.g. an issue with infrastructure, load balancers, or framework etc. I would like to be able to associate such findings (or at least an endpoint) with multiple products instead of having to duplicate the finding for each product.

**Comment by devGregA** [comment]
Hi @anakin1 thank you for submitting these issues! I agree both would be useful features. Right now we're pretty backlogged :( hopefully we can get around to it sooner rather than later.

**Comment by aaronweaver** [comment]
We should re-visit that discussion on findings to products. @YSaxon had put together a good proof of concept on doing just that.

**Comment by YSaxon** [comment]
Just to clarify, my proof-of-concept was for the related idea of making Product a field of Finding, rather than what it is now: an inheritance from its Test's Engagement. This way a finding found during an test of productA could be assigned to productB without having to create a duplicate (and fictitious) engagement and test for productB.

I like the idea of making it a many-to-many, but it won't be quite as easy.

The essence of what I did was just 3 steps:
https://github.com/OWASP/django-DefectDojo/commit/4ca314229828e5486fdf340c8f9d1c4f4c2a67af - add the field
https://github.com/OWASP/django-DefectDojo/commit/17145fe729d3e1368090bb55f818c4d169ea212b and https://github.com/OWASP/django-DefectDojo/commit/f3ab0d1a91e220187f82be115934d8cf865f5fe6 - redirect all references to product, doable with two project-wide find/replaces.

Many-to-many will be probably be more complicated. For each existing reference to product, you will need to decide, and code, which of the many products a given finding might be linked to are meant. When filtering findings by product you'll probably want to include findings that have ANY linkings to selected products. When deciding if a user is authorized to see a finding, you might want to ensure that the user is authorized to see ALL products a given finding is associated with. For some metrics, you might want to only count findings toward a SINGLE product so as not to wind up double counting some findings.
