### ISSUE TITLE
Severity filter is not working in the Findings views

### ISSUE THREAD

**Issue by ycrumeyrolle** [DefectDojo/django-DefectDojo#1874]
**Bug description**
In the findings view, the Severity filter is not working correctly:
When the filter is set to Medium (severity=Medium) and there are existing Medium finding, the view display all the Medium findings. Fine. 
When filter is set to Bob (severity=Bob) and there are **no** existing Bob finding, the view display all the findings without any filtering.
The issue is annoying with the __Critical Findings__ view that display findings since I do not have critical findings.

**Steps to reproduce**
1. Go to any Findings View
2. Filter by a non-existant finding severity
3. All the findings are displayed

**Expected behavior**
The correctly filtered view.

**Environment information**
DefecrDojo 1.5.4 RC6

**Comment by valentijnscholten** [comment]
Could you try with dev branch? master is very old.

**Comment by valentijnscholten** [comment]
If I understand django-filter correctly, the problem is in `filters.py`.

```
        self.form.fields['severity'].choices = self.queryset.order_by(
            'numerical_severity'
        ).values_list('severity', 'severity').distinct()
```

The filter tries to be helpful and only put the severities in the multiplechoice filter that are applicable to the findings in the current resultset.
If there are no critical findings, this means the `severity=Critical` parameter is ignored/disposed, resulting in no filter on severity at all.
I can't find any proper documentation on this filter. Also I think it doesn't have any real benefit to limit the amount of entries in the severity choice filter, so it might be easiest to just always put all 5 severities in there?

**Comment by valentijnscholten** [comment]
OK, so I don't think there's anyway the current setup can work correctly with (Multiple)ChoiceFilter. I also saw that there is already a SEVERITY_CHOICES constant that is already used in a lot of places, so I went ahead and updated the remaining occurrences of the severity multiplechoicefilters to use that.

Please let me know if this fixes your issue once the PR has been merged.

**Comment by valentijnscholten** [comment]
works now
