### ISSUE TITLE
Validate a finding exclude it from anything

### ISSUE THREAD

**Issue by ycrumeyrolle** [DefectDojo/django-DefectDojo#1875]
**Bug description**
When checking the box "Verified" in a finding, this finding is excluded from "Open findings". 
The metrics are excluding this finding from the findings count.
The score grade is going crazy and switch from C grade to F grade on a testing product.

**Steps to reproduce**
1. Go to findings
2. Update the status of a finding to "Verified"
3. Go back to the product home
4. See the metrics and the score grade

**Expected behavior**
A verified finding should be not be counted as a closed finding !

**Environment information**
DefectDojo 1.5.4 RC6

EDIT: Update the expected behavior

**Comment by valentijnscholten** [comment]
I can see it happening also yes, the metrics on the view product pages are all zero if all findings are verified. But if I uncheck the verified for all findings, they turn up in the metrics.
Somebody reported this on slack also today or yesterday,

**Comment by valentijnscholten** [comment]
Quickfix in #1896 

There are more places where I think findings are only included in metrics when they are NOT verified. This sounds counter intuitive to me, but I would like to check with the other developers / owners what the idea of this verified field was before changing a lot of queries.
I do think it makes sense to change this one query here because the product details page is probably used a lot and currently never shows any findings, unless you mark them as NOT verified.

My understanding until now was that a finding can be active, but:

not verified: it is active but someone has to confirm it is real and not false positive, out of scope, duplicate, ... depending on the context it might make sense to include this in metrics or not or separate.
verified: it is active and confirmed so it definitely has to be included in metrics.

Maybe @aaronweaver @devGregA @mtesauro know what the original idea/purpose of active and verified was?

**Comment by valentijnscholten** [comment]
BTW that the grade goes down once you mark a finding as verified makes sense I think, so there is no change to that logic in the PR.

**Comment by dougmorato** [comment]
@madchap Since you did the amzing work to get us False Positive and other metrics added, I think a discussion on "What a Open Finding means" needs to be had.

In my mind: Open = Any active finding, independent if they are verified or not, even if they are in "draft" state (not yet confirmed/verified)

For me, it even goes to the point that if the finding is Accepted (as in risk acceptance), the actual finding is not mitigated, so in my mind the finding remains counting as  Open+Verified, because if the compensating control is no longer effective (down/removed/altered) OR the exception for the risk acceptance expired, the vulnerability still is present and still can be exploited

**Comment by dougmorato** [comment]
Pasting my comment from the PR
Locations where this needs the definitions to be settled:
https://github.com/DefectDojo/django-DefectDojo/blob/dev/dojo/product/views.py#L194
https://github.com/DefectDojo/django-DefectDojo/blob/dev/dojo/product/views.py#L205 
https://github.com/DefectDojo/django-DefectDojo/blob/dev/dojo/product/views.py#L240

In my mind (and what I've done locally on my prod instance), these line ( verified=.... ) needs to be removed altogether, because my interpretation of an open finding is the following: 

- An active finding (active=True)
- that is verified OR not verified (findings that have yet to be confirmed) 
- AND is not out of scope (out_of_scope=false)
- AND is not duplicate (duplicate=False)
- AND is not mitigated 
- AND is not false positive

@madchap  Need your interpretation here as well

**Comment by madchap** [comment]
> @madchap Since you did the amzing work to get us False Positive and other metrics added, I think a discussion on "What a Open Finding means" needs to be had.

I rarely do anything amazing unfortunately :)

> In my mind: Open = Any active finding, independent if they are verified or not, even if they are in "draft" state (not yet confirmed/verified)

I agree.

> For me, it even goes to the point that if the finding is Accepted (as in risk acceptance), the actual finding is not mitigated, so in my mind the finding remains counting as Open+Verified, because if the compensating control is no longer effective (down/removed/altered) OR the exception for the risk acceptance expired, the vulnerability still is present and still can be exploited

I also agree.

We should document this somewhere.
