### ISSUE TITLE
Simple search should allow to chain at least 2 criteria

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#2081]
**Is your feature request related to a problem? Please describe**
Example: When wanting to search for a CVE scoped to only a specific product, one would want to do something like:

`product:"my product" 'CVE-2016-1000031'`

This would return findings results matching that CVE (single quotes there to work around the database limitation of search with hyphens, see https://github.com/DefectDojo/django-DefectDojo/issues/1092) only within the specified product.

Today, it's not possible to have that result.

**Describe the solution you'd like**
For starters, being able to scope with at least one search operator (e.g. using `product:`) and an arbitrary search string afterwards to yield results scoped to the search operator would be great.

**Describe alternatives you've considered**
Use the API and own script...

**Comment by ccojocar** [comment]
I think this will require a basic query processor which should break up a complex search query (e.g. with 2 terms) into 2 district queries. 

The following keywords are supported: `finding`, `template`, `test`, `product`, `tag`, `endpoint`, `engagement`, `language`, `technology`. They can be specified using the the syntax `keyword: "search term"`. The second term can be introduced with something like `keyword: "search term" AND "search term"`, for instance:

```
product: 'my product' AND 'CVE-2016-1000031'
```

It would be also possible to use just whitespaces instead of using a logical operator such as `AND` how is proposed in the description. 

Also the current implementation would require some refactoring, it seems that either is able to search within a model type (e.g. product) or it searches throughout all models when no prefixed keyword is provided.  See https://github.com/DefectDojo/django-DefectDojo/blob/134506be919449575b9820dc7ae006391a8bde65/dojo/search/views.py#L52

What would it be the preferred query format?

**Comment by valentijnscholten** [comment]
#2861 will make things a bit better as you can now filter explicitly on fields. Or you can just enter product names in the query box and get results as product name is now better indexed.

**Comment by valentijnscholten** [comment]
#3449 again made this a bit better
