### ISSUE TITLE
Dependency Track automation

### ISSUE THREAD

**Issue by zorianix** [DefectDojo/django-DefectDojo#2261]
Hi is there a way the dependency track result could be automatically pushed or pulled to defectdojo

**Comment by zorianix** [comment]
well i was just comparing this with Threadfix , whereby they have a plugin which if you just enable and add details of the DependencyTrack , it will pull everything and will just create results on the fly, well just something which can be added to DD too, i did use the apis, but its tedious ,even from automation point , using something like jenkins too

**Comment by zorianix** [comment]
@mtesauro But that will not be auto synced , if something can be solved around autosyncing portion

**Comment by valentijnscholten** [comment]
There is a parser to import dependency track reports:https://github.com/DefectDojo/django-DefectDojo/blob/dev/dojo/tools/dependency_track/parser.py Not sure if it's still 100% up-to-date. But making it work should be fairly easy.

**Comment by devGregA** [comment]
I thought we had done a good job of documenting how to automate imports. Since the parser already exists, I don't see anything to action. We've talked about creating this functionality as part of the UI in "Scans 2.0", but there isn't a timeline or resources allocated at this time. I don't think I need to archive this issue since we have it documented elsewhere.
