### ISSUE TITLE
Support search on MySQL InnoDB

### ISSUE THREAD

**Issue by kareem-DA** [DefectDojo/django-DefectDojo#2280]
**Is your feature request related to a problem? Please describe**
I tried to do a stand-alone install with a MySQL database hosted on GCP.  When I ran the setup.bash script, I get an error that the configuration of MySQL in GCP doesn't support MyISAM.  

**Describe the solution you'd like**
Add Support for InnoDB

**Describe alternatives you've considered**
I am trying PostgreSQL, but MySQL looks better supported by DDJ.

**Comment by madchap** [comment]
In my setup using AWS RDS, all tables are innoDB except the `watson_searchentry` one, which I found odd. But I am using a tweaked docker-compose deployment right now.

@mtesauro may know more?

**Comment by valentijnscholten** [comment]
django watson (the search index/engine DD uses) does not support InnoDB: https://github.com/etianen/django-watson/issues/120. The table is generated by django watson using a migration. You could try to set it to InnoDB and see how far you get.

**Comment by madchap** [comment]
I am going to close this, since it is not fixable really. The library in use -- django-watson -- is not using it. We've really looked at how to work around it, but aside using an outside Elasticsearch or Postgres capabilities, nothing much unfortunately.

I am myself moving to PostgreSQL since I am moving DD on GKE, and our helm is based on that. I would imagine that support for Postgres will be come better and better -- even though it seems to work very well right now.

NB: https://github.com/dimitri/pgloader worked great to migrate the data, by the way.
