### ISSUE TITLE
Postgres installation fails while setting up Single Server

### ISSUE THREAD

**Issue by Chan9390** [DefectDojo/django-DefectDojo#2372]
**Bug description**
When I select postgresql as the database type, during the installation process "mysql" binary is used to set the root password of postgres. As mysql was not present on the clean install, the installation fails.

**Steps to reproduce**
Steps to reproduce the behavior: Simply select install type as Single-Server and database type as PostgreSQL.

```
$ sudo ./setup.bash

Select install type: (1) Single-Server, (2) Dev Install or (3) Stand-alone: 1
Select database type: (1) SQLite, (2) MySQL or (3) PostgreSQL: 3
...
...
==============================================================================
  Starting PostgreSQL server
==============================================================================

chown: invalid user: ‘mysql:mysql’
Failed to start mysql.service: Unit mysql.service not found.

==============================================================================
  Checking for existing DefectDojo database dojodb in PostgreSQL
==============================================================================

==============================================================================
  Seting root password for new PostgreSQL install
==============================================================================

/home/badshah/django-DefectDojo/setup/scripts/os/linux.sh: line 138: mysql: command not found
/home/badshah/django-DefectDojo/setup/scripts/os/linux.sh: line 139: mysql: command not found
==============================================================================
  Database named dojodb in PostgreSQL not found, creating...
==============================================================================

/home/badshah/django-DefectDojo/setup/scripts/os/linux.sh: line 168: mysql: command not found
##############################################################################
  ERROR: Failed to create new dojodb in PostgreSQL for DefectDojo, exiting...
##############################################################################
```

![image](https://user-images.githubusercontent.com/12944530/82123780-d0bc4f00-97b8-11ea-9161-51c54e50e882.png)

**Expected behavior**
When PostgreSQL is used as the database, `psql` should be used to set the root password.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [x] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Ubuntu 18.04
 - DefectDojo Commit Message: `027d879: Fixes to plantuml action [2020-05-09 06:50:52 +0200]`

**Comment by Chan9390** [comment]
This is similar to the issue #2282 but here I am trying to setup postgres on my local machine instead of remote machine.

**Comment by valentijnscholten** [comment]
Looking at that script I think the postgres variant of the install script was never completed.

**Comment by valentijnscholten** [comment]
Are you in the position to try and fix the script, i.e. use `psql`?

**Comment by Chan9390** [comment]
I am not very familiar with `psql`

**Comment by valentijnscholten** [comment]
@mtesauro I think this can be considered a bug,e ven in 1.60. What's your view on this? Is this an easy fix for you, or do you want to document this limitation?

**Comment by immewnity** [comment]
I'm getting the same (essential) error while trying with SQLite as well... Only MySQL seems to work.

**Comment by mtesauro** [comment]
To be honest, setup.bash was created before PostgreSQL support was in DefectDojo so that was stubbed out but never really completed.  That said, you can setup an empty database in PostgreSQL with a user/password for that database and pass that info into the installer to make it work for the time being.  You could that use the env variables to 'tell' the installer about PostgreSQL:

`# PROMPT="false" DB_TYPE="PostgreSQL" DB_EXISTS="true" DB_USER="dojodbusr" DB_PASS="dbuserpass" DB_NAME="dojodb" DB_HOST="localhost" DB_PORT="5432" ADMIN_PASS="djadmin" ./setup/setup.bash
`

Sorry, very long command but you only have to do it once.  I guess you could also use a container running PostgreSQL with the above also - you'd just have to adjust the ENV variables accordingly.

There's loads of not so awesomely documented env variables supported by setup.bash at https://github.com/DefectDojo/django-DefectDojo/blob/master/setup/scripts/common/config-vars.sh

I have done the above and know it works with a single VM DefectDojo install with PostgreSQL already setup and ready on the same VM.

**Comment by mtesauro** [comment]
> I'm getting the same (essential) error while trying with SQLite as well... Only MySQL seems to work.

I honestly would like to drop support for SQLite completely - I know that Django supports it but even for a dev instance MySQL/PostgreSQL work fine and don't have high hardware requirements.  To me, the added support complexity should be avoided since the alternatives are straight forward and are open source with low minimal hardware requirements.

**Comment by madchap** [comment]
By the way and for a heads-up notice, `setup.bash` will be EOL/deprecated at the end of this year.

@mtesauro would probably love to have some godojo user, need to advertise for that ;-)

**Comment by mtesauro** [comment]
Agreed about godojo - I just need to get it working again after a MAJOR refactoring (as part of the ENV variable work I've been doing).

I know the early version works fine for Ubuntu + MySQL or any DB if it's already exists - e.g installed and setup locally or on a remote host.

Brave souls can find a very early version at https://github.com/mtesauro/godojo/releases

Short version is you need only godojo + dojoConfig.yml to do an install.  godojo pulls the DefectDojo from Github (source for a branch, a specific commit OR a specific GH release).

**Comment by valentijnscholten** [comment]
setup.bash is deprecated and will no longer be maintained. we have added a check which provides a clear error that postgres db has to be created manually before running the installer.
