### ISSUE TITLE
Defectdojo do not connect to Cloud SQL with SSL enabled. (postgresql)

### ISSUE THREAD

**Issue by 676031** [DefectDojo/django-DefectDojo#2549]
**Bug description**
I have found the steps to add “root-ca.pem” to establish ssl connection to AWS RDS.
In my case I'm working with GCP and there I have (server-ca, client-ca and client-key) needed to configure ssl connection for PostgreSQL. As I know there is no root-certificate.
It will be very helpful to have some explanation of how to establish SSL connection in this case.

**Steps to reproduce**
1. Create Cloud SQL (postgres) and enable only SSL connection,
2.Run Ubuntu 20.04LTS instance and git clone defectdojo repo.
3. Edit Dockerfile.dojo to copy server-ca, client-ca and client-key
4. Edit dojo/settings/settings.dist.py with these lines :     
DATABASES['default']['OPTIONS'] = {
    'ssl': {
        'key': '/etc/ssl/certs/client-key.pem',
        'cert': '/etc/ssl/certs/client-cert.pem',
        'ca': '/etc/ssl/certs/server-ca.pem'
        }
    }

**Expected behavior**
Dashboard is available and defectdojo is available to connect to database with SSL after docker-compose-build and docker-compose up .

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 20.04]

**Screenshots** (optional)
![Annotation 2020-06-14 032938](https://user-images.githubusercontent.com/20356833/84582093-27d13600-adf0-11ea-922b-f2613aba14c5.png)

**Console logs** (optional)
initializer_1   | subprocess.CalledProcessError: Command '['psql', '-U', 'root', '-h', '35.34.22.112', '-p', '5432', 'defectdojo']' returned non-zero exit status 2

**Comment by valentijnscholten** [comment]
This is more like a general database connectivity question, but maybe someone here can help. At first glance it looks strange that you have 'IP-address' in that log line instead of an IP or hostname?

**Comment by 676031** [comment]
> This is more like a general database connectivity question, but maybe someone here can help. At first glance it looks strange that you have 'IP-address' in that log line instead of an IP or hostname?

There is a real ip-address)))) I've just hide it)) so that is not a problem

**Comment by 676031** [comment]
> This is more like a general database connectivity question, but maybe someone here can help. At first glance it looks strange that you have 'IP-address' in that log line instead of an IP or hostname?

I have updated some info

**Comment by 0xE2** [comment]
I suppose that this error is a consequence of the next call chain:
docker runs entrypoint script (entrypoint-initializer.sh) which runs the following command:
`python3 manage.py dbshell`
**dbshell** is the internal Django function. When it tries to access DB without appropriate SSL certs and keys, an error occurs.
You can try out one of these solutions:

1. Add ENV variables which will override the location of the certificates and key files:
Update Dockerfile.django:
```
ENV PGSSLROOTCERT /etc/ssl/certs/server-ca.pem
ENV PGSSLCERT /etc/ssl/certs/client-cert.pem
ENV PGSSLKEY /etc/ssl/certs/client-key.pem
```
Also, it might be required to change owner of those files to 1001 and set permission to 600. Update **USER root** block with these lines:
```
RUN chown 1001:1001 /etc/ssl/certs/server-ca.pem
RUN chown 1001:1001 /etc/ssl/certs/client-cert.pem
RUN chown 1001:1001 /etc/ssl/certs/client-key.pem
```
See more about env variables [here](https://www.postgresql.org/docs/current/libpq-ssl.html)

2. Put certs and key into ~/.postgresql/ folder:
For some reason, this won't work for me (I guess this is because all operations in the container are performed by user 1001, which kinda does not exist)
Update Dockerfile.django:
```
COPY server-ca.pem /.postgresql/root.crt
COPY client-cert.pem /.postgresql/postgresql.crt
COPY client-key.pem /.postgresql/postgresql.key
```

3. Update Django version and settings.dist.py:
[This Django fix](https://github.com/django/django/commit/5b884d45ac5b76234eca614d90c83b347294c332) allows dbshell to pass SSL related options to underlying CLI tool. For now, DD using 2.2.13 version of the Django framework and this version does not contain a fix. When I tried to update Django to version 3.0.6 I struggled with components compatibility issues, so be aware.
Then you can update settings.dist.py:
```
    DATABASES['default']['OPTIONS'] = {
        'sslmode': 'verify-ca',
        'sslcert': '/etc/ssl/certs/client-cert.pem',
        'sslkey': '/etc/ssl/certs/client-key.pem',
        'sslrootcert': '/etc/ssl/certs/server-ca.pem',
    }
```
