### ISSUE TITLE
Active user permission to add finding

### ISSUE THREAD

**Issue by kbonato** [DefectDojo/django-DefectDojo#2944]
hello, I'm using the new version 1.8.0 and I'm having a hard time.

I created a user with the "Active User" permission
And I associated a project with it, but the user cannot add vulnerabilities, even though I put this in the admin.

![image](https://user-images.githubusercontent.com/26029330/94715096-6816de80-0323-11eb-8958-4fd5858b6579.png)
![image](https://user-images.githubusercontent.com/26029330/94715155-76fd9100-0323-11eb-88da-a821fe76be9d.png)
![image](https://user-images.githubusercontent.com/26029330/94715166-7a911800-0323-11eb-8b16-22427515e226.png)

**Comment by madchap** [comment]
The django permissions within Django's admin panel will not work in the UI (they could work through the API, because of the way dojo is written today).

In settings.py, you have 2 variables initially set to `False`:

```
DD_AUTHORIZED_USERS_ALLOW_CHANGE
DD_AUTHORIZED_USERS_ALLOW_DELETE
```

Change them to `True`, and this should solve your issue.

Let us know.
Cheers.

**Comment by madchap** [comment]
Starting to document settings.py variables effort at https://github.com/DefectDojo/Documentation/pull/130

**Comment by kbonato** [comment]
Hi madchap, 

This file? django-DefectDojo/dojo/settings/settings.dist.py ?

**Comment by kbonato** [comment]
Hi @madchap 
I am using dojo in production mode and set True, but dont work, have other solution?

**Comment by Maffooch** [comment]
`DD_AUTHORIZED_USERS_ALLOW_CHANGE` and `DD_AUTHORIZED_USERS_ALLOW_DELETE` do not allow for adding findings, but `DD_AUTHORIZED_USERS_ALLOW_STAFF` will allow that and other things. It is also located in settings.py

**Comment by kbonato** [comment]
@Maffooch Works!!!
Thanks

**Comment by childsc** [comment]
@madchap I am new to defect dojo, Can you confirm what you mean with this:
`The django permissions within Django's admin panel will not work in the UI (they could work through the API, because of the way dojo is written today).`

so this means that with regards to defining the user and or group permissions in /admin no longer works?
As I am trying to understand how to set alternative permissions there. 

Would this mean that the only way to fine tune access would be through the settings.py ?

I am trying to find documentation about how to fine tune the authorisation for our new installation and to make suggestion of how one can go about providing different types of access.
