### ISSUE TITLE
Don't delete duplicates when deleting an original

### ISSUE THREAD

**Issue by Wadeck** [DefectDojo/django-DefectDojo#3057]
**Bug description**
In a single engagement, I had 3 tests, with 1, 3 and 12 findings respectively. The 1 and 3 findings were contained in the 12 findings (just sub set). When I deleted the first two tests, I saw my third test reduced from 12 to 9 findings.

**Steps to reproduce**
As the situation happened just before a correction of an unrelated issue, I did not try to reproduce the problem. I imagine at this point that we can see exactly the same behavior if we import a test two times, with the first one being only a sub set and then the second time the full report. If we delete the first (sub set), the second one will be impacted.

**Expected behavior**
If there is a duplicate, when I delete the test containing the original, I expected the duplicate finding in another test to be not deleted, or at least to have an option to unlink such duplicate to not loose information.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo Commit Message: [use `git show -s --format="[%ci] %h: %s [%d]"`]

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

**Comment by valentijnscholten** [comment]
When an "original finding" is deleted, all duplicates are deleted by default. Would be good to inform the user or make it optional. But the question then is if the original is deleted, what should happen with the remaining duplicates? Should they be no longer marked as duplicate? Or should the "oldest" of them become the new original for all the rest so they can stay duplicate?
One option is to block deletion of originals as a way to force the user to reorganize the duplicates differently to "free" the original of any duplicate links so it can be deleted safely.

**Comment by devGregA** [comment]
Interesting, originally, delete was only introduced to remove a finding that was created in error. The original thought was findings that aren't a mistake should always be closed, for record keeping purposes. Then closed vulnerabilities could be purged after a period of time 1 year, two years, etc. I'm not really sure why someone would delete a finding, other than if it was made in error. I agree with Valentijn's evaluation that the behavior is weird. If we simply made a system setting to toggle the behavior, the issue is that duplicates won't know the original is deleted and will have a broken link. If the duplicates aren't deleted, there would need to be a subroutine to update a new 'original' finding.

**Comment by valentijnscholten** [comment]
fix in dev / 1.15.0
