### ISSUE TITLE
Support for JFrog XRAY Unified (new version of XRAY)

### ISSUE THREAD

**Issue by ofg** [DefectDojo/django-DefectDojo#3424]
**Scanner Name**

JFrog XRAY (Unified version) https://www.jfrog.com/confluence/display/JFROG/Xray+Security+and+Compliance

JFrog Xray scans your artifacts, builds and Release Bundles for OSS components being used, and detects security vulnerabilities and licenses in your software components. The results of this scan are then displayed across the JFrog Platform.

XRAY Unified has a different JSON export format then XRAY 2.x.

**Sample File**
Sample JSON report  attached ...
[Vulnerabilities-Report-XRAY_Unified.zip](https://github.com/DefectDojo/django-DefectDojo/files/5651948/Vulnerabilities-Report-XRAY_Unified.zip)

**Comment by damiencarol** [comment]
@ofg I can create you a new kind of importer but I want to understand the difference between JFrog XRAY ***Vs*** JFrog XRAY (Unified version)
Is this new "unified" version will replace the old one?

**Comment by ofg** [comment]
Hi @damiencarol , I am not completely familiar with the product strategy of JFrog. But what I understand from the user documentation https://www.jfrog.com/confluence/display/JFROG/ : There is an "old" version XRAY 2.x and a current version "JFrog Unified Platform". We are using the current version. The export looks like the one attached and it differs to the export stored here: https://github.com/DefectDojo/sample-scan-files/tree/master/jfrogxray

**Comment by damiencarol** [comment]
@valentijnscholten you can assign it to me, I will create an importer for this one.

**Comment by LithiumBloom** [comment]
Hi, any update on this one? If not, could I get some guidance on how to fix myself? Is it just a matter of creating a new parser similar to django-DefectDojo/dojo/tools/jfrogxray/parser.py or would I need to do something else to get the app to pick up the new importer? I'm not too familiar with factories unfortunately

**Comment by valentijnscholten** [comment]
You can follow our guide: https://defectdojo.github.io/django-DefectDojo/contributing/how-to-write-a-parser/ but the cookie cutter has some pending PRs I think to improve it.
Another good inspiration are the latest merged PRs with label "Import Scan": https://github.com/DefectDojo/django-DefectDojo/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+label%3A%22Import+Scans%22

**Comment by damiencarol** [comment]
Hi @LithiumBloom , I'm still working on it as we have Xray running at my company (so real data to test). It's not finished yet, I'm trying to use the API.
If you have some doc focused on the API, I'm interested.

**Comment by LithiumBloom** [comment]
Hi @damiencarol yeah I've been working on this and I think its pretty much done, just gonna do a few sanity checks on Monday before working out how to do the pull request. Hope it wasn't wasted effort if you're working on it too but oh well haha. I'm not sure what you mean by the api, do you mean defect dojo getting the data directly from xray's api rather than having to manually upload the Json file? That does sound better if it can lead to a more automated solution =)

I don't know anything about the xray api unfortunately, although I think my company has been in contact with the artifactory vendors to try to get some bug fixes, I can try to get you an email address for them if you think that would be useful?

Thanks for your work in making the parsers, it was pretty straightforward once I'd got my dev environment set up ^^

**Comment by damiencarol** [comment]
Awesome! I'm glad you can contribute on this part.It's a different approach but it's a good first step.
Will support/comment your PR
