### ISSUE TITLE
Enhance (full) risk acceptance

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#3441]
**Is your feature request related to a problem? Please describe**
## Full risk acceptance acceptance Form

- While on a specific finding and clicking `Add full risk acceptance`, the default title is not ideal.
- While on a specific finding and clicking `Add full risk acceptance`, the landing screen does not pre-select the finding we were looking at. You have to find it again in the list.
- Today, the risk acceptance screen is potentially lacking inputs, and may push people to have another document outside of defectdojo, causing duplicate work.
- When viewing the risk acceptance once it's been saved, the compensating controls are shown in a super small column.
- When viewing the risk acceptance, a staff or superuser cannot edit it.

## SLA (when enabled)
- When a finding is risk-accepted, its "SLA counter" does not get reset, as SLA is based on the finding's creation date. However, when a temporal risk acceptance is made for a finding and expires, the SLA should start over again.

**Describe the solution you'd like**
## Form enhancements
- While on a specific finding and clicking `Add full risk acceptance`, the landing screen should come up with a better default title.
- While on a specific finding and clicking `Add full risk acceptance`, the landing screen should come up with the finding pre-selected at least. Eventually, maybe 2 inputs: the edited finding should just be a default (and not un-selectable, like in a label, since we're coming from there), while other potential findings that could be added to the acceptance be an optional list.
- Text fields, which can be quite large should have the markdown edit bar when editing the risk acceptance.
- These larger text fields should be rendered in a bigger space when viewing the risk acceptance.
- Should be able to edit the risk acceptance when viewing it (`e` keyb shortcut and/or menu)

Add the following fields:
- Risk acceptance actual (business) decision as a choice between: mitigate, fix, avoid, accept, transfer (mandatory) with description help text for each.
- A similar field as above, but for engineering/product security recommendation -- typically would show the a "fix" vs "avoid" or "accept" decision.
- Free Text field for "Business justification for acceptance" -- engineering can probably have certainly have its own recommendations within the notes section, even though it could be considered to explicitly create a field for that too.

## SLA
- In order to be more flexible here, introduce a `sla_start_date` (or otherwise named) in the Finding model and base sla calculation on that field instead of the finding's creation date. Create a administration migration for it by copying the finding's creation date onto it for initialization.

**Describe alternatives you've considered**
Manually maintain a document outside of defectdojo and put the link in the defectdojo risk acceptance notes. A cumbersome task.

**Additional context**
The idea is to be able to maintain risk acceptance entirely in defectdojo for anything product security related.

Automating reminders for temporal risk acceptance expiration, automating rescheduling of risk acceptance or threat model exercises, export risk acceptance data to external dashboard or reporting tool.

**Comment by valentijnscholten** [comment]
Sounds good to me. One thing I was thinking about. I think a more generic  'deadline' field instead of 'sla_date' would be helpful. At finding version it can be set based on sla days. But on risk acceptance it could be set to the end date of the acceptance. When it expires it can be {optionally) set again to be another 'sla days' in the future. 
It would also allow us to have a possible override feature where users with the right permission could extend the deadline.

**Comment by alles-klar** [comment]
Sounds good.

But I prefer to make it configurable if the sla time should be reseted. From my point it should be not reseted because you know how long the risk is accepted. It is not an unpredictable event like a new vulnerability, so no need for an sla.

Furthermore I am not sure what happens at the moment when a risk acceptance expires. I expect the findings are marked active again, but I do not think it work this way in the current implementation.
