### ISSUE TITLE
Scan Integration 2.0

### ISSUE THREAD

**Issue by devGregA** [DefectDojo/django-DefectDojo#365]
Scan Integration 2.0 is focused on shifting our integration with uploads to APIs by extending the scan class. The biggest challenge around this feature will be the modeling. We will extend the 'Scan' model to support vuln scanners / tools.  We should be  able to get results, specify settings, and schedule scans (maybe even spin up instances for open-source tools).

**Comment by devGregA** [comment]
Extend scan for generic methods that go to celery and call a python library

**Comment by maennel** [comment]
Do I understand this issue correctly to expose a single 'Scan' endpoint (or to extend the existing one), in order to be able to POST scan results to it? 
This would ease integration with products able to call a pre-defined resource (webhook) once done scanning.

Regarding the second point of scheduling, triggering and managing scans from within DefectDojo, how would this co-exist with a CI/CD driven deployment pipeline? Assuming there is a CI/CD system in place, it should probably be the system triggering scans, with their results being aggregated in DefectDojo. I may also have missed a point so, please, don't hesitate to correct my assumptions...
