### ISSUE TITLE
Latest docker image fails at launch

### ISSUE THREAD

**Issue by raajheshkannaa** [DefectDojo/django-DefectDojo#434]
### Issue Type 
- Bug

### Description
- The latest docker image from appsecpipeline/django-defectdojo fails when launching complaining 'No passwd entry for user 'dojo''

### Environment:
- Docker in Windows 7

**Comment by Mason-Fan** [comment]
i found the issue also occurs in Linux docker

**Comment by aaronweaver** [comment]
@Mason-Fan @raajheshkannaa This issue should be fixed, if you wouldn't mind confirming.

Thanks!

**Comment by devGregA** [comment]
Please feel free to reopen if you continue to have issues.

**Comment by Mason-Fan** [comment]
@devGregA   @aaronweaver  thanks for your help. the issue is fixed. 
but when i run the command 
docker run -it -p 8000:8000 appsecpipeline/django-defectdojo bash -c "export LOAD_SAMPLE_DATA=True && bash /django-DefectDojo/docker/docker-startup.bash"
according to the doc "login with the credentials shown in the terminal.".  but there is no credentials shows.  i tried sometime and found "admin:admin" can login. maybe you can fix the issue or update the documentation.
