### ISSUE TITLE
Add Meta Data / Additional Information to API?

### ISSUE THREAD

**Issue by xthk** [DefectDojo/django-DefectDojo#459]
### Issue Type

- [ ] Bug
- [X] Enhancement

### Add Meta Data / Additional Information to the API

As an API user I'd like to have "Additional Information" or meta data via the API. This should be applied to products, and endpoints.

An example use case would be to push company specific information to DefectDojo, e.g. business unit, additional contact information, etc.

I'd love to see all CRUD (create, read, update, delete) operations for meta data.

**Comment by Horst88** [comment]
Hi,
this would be great and also comply with, **Tools need to have an API so that the 'All the things' can be automated**, see https://www.owasp.org/index.php/OWASP_AppSec_Pipeline#tab=Pipeline_Tools

**Comment by jpbowie** [comment]
A few weeks ago I wanted to create a report based on some product metadata and tag queries so I implemented a few API calls that I could use instead of directly accessing the database.
The calls aren't very user friendly and may expose more internal details than desired, but if anyone is interested I can share the code or submit a pull request.  The product metadata API specifically allows GET requests to search by custom field (id, name, etc.), custom field value (id, value, etc.), and/or product id (object_id).  Here's what the request and response body look like:
Request URL
http://localhost:8000/api/v1/product_metadata/?field__name=Technology&value__contains=SQL
Response Body
{"meta": {"limit": 20, "next": null, "offset": 0, "previous": null, "total_count": 1}, "objects": [{"field": "/api/v1/product_metadata_fields/8/", "field_name": "Technology", "id": 9, "object_id": 3, "product_name": "Test Product", "value": "C#, SQL"}]}

**Comment by devGregA** [comment]
Completed in PR.
