### ISSUE TITLE
ZAP & trivy import errors

### ISSUE THREAD

**Issue by alexr3** [DefectDojo/django-DefectDojo#5485]
**Bug description**
When manually importing ZAP and Trivy reports in different formats (json, xml, etc)

**Steps to reproduce**
1. Go to 'All products'
2. Choose product
3. Click on 'Findings' - 'Import Scan Results'
4. Choose and attach file
5. Click on 'Import'
6. See the following errors:
"An exception error occurred during the report import:Expecting value: line 1 column 1 (char 0)" - trivy (xml/json/csv/sarif)
"An exception error occurred during the report import:mismatched tag: line 13, column 2" - ZAP (xml/json/html)
7. As a result total findings is zero (Engagement - Choose Engagement - Total findings)

**Expected behavior**
Correct information with findings

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**

**Logs** 

**Sample scan files**

**Screenshots**

**Additional context** (optional)

**Comment by StefanFl** [comment]
Hello @alexr3, please provide log files for these errors. Without them it's hard to see what's going wrong.

**Comment by StefanFl** [comment]
I tested the Trivy import with a scan using the latest Trivy version and it worked fine

**Comment by valentijnscholten** [comment]
And please provide sample files to reproduce.

**Comment by StefanFl** [comment]
Closed due to inactivity

**Comment by Ashoknation** [comment]
Hi,

I would like to answer for this error, because today i got the same error when i am importing my html report that i have extracted for the OWASP ZAP tool and i want to import in DEFECT DOJO tool.

I was not selecting ZAP scan in the scan type column and after selecting ZAP Scan my report got imported in the DEFECT DOJO tool.

**THATS HOW I SOLVED MY ERROR TODAY**

Thankyou
