### ISSUE TITLE
trivy defectdojo image scan

### ISSUE THREAD

**Issue by saldam72** [DefectDojo/django-DefectDojo#5907]
Hello team,
I have scanned DefectDojo 2.6.2 official image on Docker Hub Repository with Trivy 0.23 and I have found some vulnerabilities of CRTICAL (14) and HIGH (53) severity.

In case of need, I'm available to send you reports.

P.S. I have scanned also 2.7.1 and I have found again some vulnerabilities of CRTICAL (11) and HIGH (50) severity.

Regards,
Sal

**Comment by valentijnscholten** [comment]
Did you triage the issues? These containers scans usually generate lots of noise due to incorrect version detection. We're running the latest version of alpine and all python packages, so not much more we can do. There may be some vulnerabilities in some python packages, but these have been triaged by use and are updated in `dev` already and part of the next release.
If you feel there are some real vulnerabilities still in dev, or critical/highs in master, that need attention, please let us know via the security disclosure process mentioned in our bug report template.

**Comment by saldam72** [comment]
Hi Valentijn,
Trivy is the open source version of Aqua Security and is a scanner for known vulnerabilities in container images.

We are also running a static and dynamic application security testing and if we find any vulnerabilities we will let you know via the security disclosure process.

regards,
Sal

**Comment by manuel-sommer** [comment]
I guess this can be closed @mtesauro .
