### ISSUE TITLE
Update IBM Appscan to HCl AppScan

### ISSUE THREAD

**Issue by luminescence69** [DefectDojo/django-DefectDojo#6035]
**HCL AppScan**
AppScan has been bought over by HCL. The reporting format has been updated and is not compatible with the existing AppScan importer.

**Sample File**
Sample XML file for a test site
[Demo_Security_Report_Appscan.zip](https://github.com/DefectDojo/django-DefectDojo/files/8281489/Demo_Security_Report_Appscan.zip)

**Comment by damiencarol** [comment]
@luminescence69 which version became not compatible?

**Comment by luminescence69** [comment]
> @luminescence69 which version became not compatible?

I'm running the latest version of DD. The reporting format has changed since 2020 when HCL bought over AppScan from IBM.

**Comment by luminescence69** [comment]
@damiencarol could you advise how we can progress with this issue?
I'm happy to provide any additional information

**Comment by damiencarol** [comment]
@luminescence69 best solution here should be to create another parser. Are you able to create a PR to do this? (I can help)

**Comment by mtesauro** [comment]
@luminescence69 You could start with https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/CONTRIBUTING.md

**Comment by mhanner** [comment]
No need for a new parser.  The existing parser needs to be updated to support a slight change in the XML format: <text /> elements are now used instead of <br />.  This affects parsing the for the fix recommendation (get_findings()) and issue description (fetch_advisory_group()).

The attached patch file will load the Sample XML file attached to this bug (as well as other files).

[0001-github-issue-6035-IBM-Appscan-Parser-does-not-handle.patch.txt](https://github.com/DefectDojo/django-DefectDojo/files/9004975/0001-github-issue-6035-IBM-Appscan-Parser-does-not-handle.patch.txt)

**Comment by damiencarol** [comment]
Awesome work @mhanner ! Merged in `dev`
