### ISSUE TITLE
Correct the documentation about the default username

### ISSUE THREAD

**Issue by bewell** [DefectDojo/django-DefectDojo#642]
Please use the following template when submitting issues:

### Issue Type 
- [x] Bug

### Description
The documentation states, that the default username is `admin` / `administrator`. In reality it is `admin` / `admin`

### DefectDojo Version
Latest

**Comment by devGregA** [comment]
@bewell this was from someone changing the creds in the demo. A script was supposed to run every 24 hours to reset everything. Demo is currently down while we explore other options.

**Comment by pandyaved98** [comment]
Bug.
It's still showing that wrong password. I've tried all of the given ID & Passwords.

My Tries:
admin / admin
admin / administrator
Mylogin / password
product_owner / product_owner

**Comment by AjCaroline** [comment]
it is a new year and it seems this issue still exists...??? Can someone help? Finally after 2 weeks I got the localhost page up and now something as silly as credentials is not documented (or easily found) ANYWHERE. Help. Please. Trying to review the application but it has been EXTREMELY painful just even starting....>!   Thank you.

**Comment by caesium55ds** [comment]
Ok...I got a pointer from someone who had this same problem and figured it out.  When you start DefectDojo...a password is auto-generated.  The username is admin; but the password can be found somewhere in the output.  I'll put mine here as an example since 1) I've changed it and 2) its auto-generated so it will be different for everyone who starts DefectDojo.  As you can see I did a search for password and found it that way:   
![image](https://user-images.githubusercontent.com/43476799/73369875-53101a00-4281-11ea-8087-afab1aa871f2.png)

**Comment by Sudneo** [comment]
Hello,

for those of you who installed with Docker-compose but the couldn't find a way to login locally, I have done the following:

```
docker logs $MYSQL_CONTAINER 
```

Find the line 'GENERATED ROOT PASSWORD: some_password'

```
docker exec -it $MYSQL_CONTAINER bash
mysql -uroot -psome_password
USE defectdojo
UPDATE auth_user SET password='pbkdf2_sha256$36000$sT96yObJtsFk$F9YAJimsQqBXnff/QGLNTv100qhCNl/23hoBuNtSNZU=' WHERE username='admin';
```

This is a value that can be found in `/dojo/fixtures/dojo_testdata.json`. 

Now you can login with `admin`:`admin`.
