### ISSUE TITLE
How to backup and restore mysql database.

### ISSUE THREAD

**Issue by sergeymeleschenko** [DefectDojo/django-DefectDojo#6724]
I need to backup MySQL database from defectdojo version 2.9.0 and restore it to another machine with defectdojo version 2.13.1.
How to backup mysql database, if there some manual about this ? Where can I find info.

**Comment by mtesauro** [comment]
The easiest thing to do is take a sqldump of the DB on 2.9.0 and then restore using that dump.  A quick search will find loads of articles on how to do that for MySQL like [this one](https://www.sqlshack.com/how-to-backup-and-restore-mysql-databases-using-the-mysqldump-command/).

When you startup 2.13.1 make sure you run the migrations. If you're using docker-compose, this will 'just happen' with the initializer container.  You may want to use `docker logs -f` to watch the migrations on that container to ensure there aren't errors since you're doing a rather large version update.
