### ISSUE TITLE
Docker failure on all new Apple M1 (arm64) machines.

### ISSUE THREAD

**Issue by preston** [DefectDojo/django-DefectDojo#6767]
All new macOS machines ship with an M1 or M2 chip that uses an ARM-based instruction set, not Intel/AMD x64. Any referenced images must support a "linux/arm64/v8" option in the manifest to work for these machines. When using the `dc-up.sh` script, the docker-compose.yml file is unable to find a compatible MySQL image.

All the recent versions of the official MySQL images are built and published as multi-architecture, but the 5.x series is not. (See https://hub.docker.com/_/mysql/tags) Until this is updated or changed, the MySQL-based profiles will be likely be broken for all Apple users on recent hardware.

**Comment by 37b** [comment]
Just update the compose files. It’s what I do.

**Comment by Nirusu** [comment]
Was running into the same issues. Unfortunately, out of the box the PostgreSQL options also don't work due to https://github.com/psycopg/psycopg2/issues/1360.

Upgrading MySQL here:
https://github.com/DefectDojo/django-DefectDojo/blob/master/docker-compose.yml#L132-L133
to `mysql:8` seems to work as arm64 exist for MySQL 8.

Not sure if this exactly introduces any errors though, as I was just trying out the first time.
There seems to be #6971 but apparently upstream won't be moving to MySQL 8 for now. 

Alternatively running the images on amd64 mode on macOS likely also would work, but with a severe performance hit. For this, you can try: `export DOCKER_DEFAULT_PLATFORM=linux/amd64`

**Comment by fsbano** [comment]
Hello @Preston ,

I am using image: mysql:latest 

Best Regards,
Fábio Sbano

**Comment by manuel-sommer** [comment]
For me it works fine with postgres.
What about you @quirinziessler ?
I guess this can be closed @mtesauro

**Comment by quirinziessler** [comment]
@manuel-sommer same for me. Only on debug I get some errors regarding mailhog but everything runs fine.
Can be closed imo.
