### ISSUE TITLE
Local scanner for company business

### ISSUE THREAD

**Issue by worapojc** [DefectDojo/django-DefectDojo#6840]
**Local Scanner Type**
I would like to create a scanner for my company policy. This is not the public tools and would not fit for any one.
This scanner will scan the database setting which follow my company policy i.e. maximum number of database connections, logs level or etc.

I read this document and it needs to do a pull request, https://defectdojo.github.io/django-DefectDojo/contributing/how-to-write-a-parser/
How do I build a custom parser and deploy on my DefectDojo server?

**Sample File**
JSON file

**Comment by italvi** [comment]
Which way of deployment do you use? Please refer to https://github.com/DefectDojo/django-DefectDojo/tree/master/readme-docs for seeing the different ways and build the images locally and deploy your own DefectDojo instance. At least this is how we are working because we also wrote a custom parser for an own application. Alternatively, if it is possible to change the output: Maybe the Generic Parser fits your needs https://defectdojo.github.io/django-DefectDojo/integrations/parsers/#generic-findings-import

**Comment by manuel-sommer** [comment]
I guess this can be closed as stale @mtesauro
