### ISSUE TITLE
JIRA webhook view has no authentication

### ISSUE THREAD

**Issue by Nilix007** [DefectDojo/django-DefectDojo#695]
### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description

The JIRA webhook view, i.e. the view to which the JIRA server will post updates, does not have any authentication so that anybody can call this webhook and manipulate data in the DefectDojo database.

See:  https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/jira_link/views.py#L26

**Comment by aaronweaver** [comment]
Thanks for bringing that to our attention. Originally, when that was created the intent was to whitelist that endpoint with an Nginx proxy. While not ideal, at the time that's all that Jira supported. Two checks have been added:

1.  If Jira is not enabled the call to the webhook will return denied
2. A system setting option has been introduce, `enable_jira_web_hook` which is disabled by default along with a suggestion to whitelist.

Since then it looks like there are some other options in later versions such as supporting JWT and possibly an add on to add an API key. I'll add to the documentation and continue reviewing options that Jira might support.
