### ISSUE TITLE
Jira 9.0+ is not supported

### ISSUE THREAD

**Issue by pna-nca** [DefectDojo/django-DefectDojo#6963]
**Bug description**
An error occurs when trying to integrate DefectDojo with Jira 9.0+, on altering product settings.

**Steps to reproduce**
0. Be sure that target Jira instance has version 9.0+.
1. Configure Jira instance in DefectDojo settings.
2. Go to the existing product and select "Settings --> Edit"
3. In Jira integration settings provide the valid settings. Press "Submit".
4. See non-descriptive error that Jira settings were not saved.

**Expected behavior**
A clear and concise error message why the error occurred.
Working without errors with Jira instances 9.0+. :)

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
 - DefectDojo version: 2.15.0

**Logs** 
No logs without DEBUG mode.
In DEBUG mode the error is "invalid JIRA Project Config, can't retrieve metadata". See also below.

**Additional context** (optional)
Jira's createmeta endpoint is deprecated since 2020, see https://confluence.atlassian.com/jiracore/createmeta-rest-endpoint-to-be-removed-975040986.html
However, Jira python module still uses it, see https://github.com/pycontribs/jira/issues/1462
DefectDojo uses jira.createmeta() call in get_jira_meta() function in jira_link/helper.py file.
Moreover, DefectDojo does not handle exception properly which may be triggered by jira.createmeta().
See pull request #6962.

**Comment by fderoubaix** [comment]
Hello,

I'm currently experiencing the same problem (DefectDojo v2.11 / Jira server v9.2 and Kubernetes deployment).

When I try to edit an existing product (id 42) in DefectDojo and set Jira integration, i've got this message : "JIRA Project config not stored due to errors."

In the logs of the uwsgi container there is this line that appears:
`- WARNING [django.request:224] Not Found: /jira/webhook/XXX`

I checked the webhook id on both sides and everything matches

In the logs of the nginx container there are a lot of connection tests with random users of my Jira instance (I don't know why the requests go through with these random users instead of the account registered in the configuration in Jira instance settings) : 

```
- "GET /alerts/count HTTP/1.1" 200 13 "https://defectdojo.xxx.com/product/42/edit" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0" "xx.xx.xx.xx"

- "POST /jira/webhook/xxx?user_id=<RANDOM USER IN JIRA>&user_key=JIRAUSER23131 HTTP/1.1" 404 15390 "-" "Atlassian HttpClient 3.0.0 / JIRA-9.2.0 (920000) / Default" "xx.xx.xx.xx"

- [error]` 10#10: *5133712 readv() failed (104: Connection reset by peer) while reading upstream, client: xx.xx.xx.xx, server: , request: "POST /jira/webhook/xxx?user_id=<RANDOM USER IN JIRA>&user_key=JIRAUSER23131 HTTP/1.1", upstream: "uwsgi://unix:///run/defectdojo/uwsgi.sock:", host: "defectdojo.xxx.com"
```

Currently, I have not found any way around this problem. If someone has a suggestion, I'm interested :)

**Comment by pmilosev** [comment]
@pna-nca I'm working on this.
I've adapted the `createmeta` API in `pycontribs` and will implement the needed changes in dd next.
I'll push everything once it's all tested.

**Comment by pna-nca** [comment]
I doubt it can be marked as closed: Jira 9 support is indeed in place, but the corresponding Python module does not support Jira 9 yet. Thus, even with this commit, DefectDojo will not work with Jira 9.
What is still required is to update dependency to pycontribs/jira module. See https://github.com/pycontribs/jira/pull/1527

**Comment by Maffooch** [comment]
@pna-nca please submit a PR the corrects the issue. Will close on your mark

**Comment by pmilosev** [comment]
I would recommend to just wait on the PR in the mentioned dependency to be merged. Otherwise the fix would be to change the dependency definition to point to the PR in pycontrib/jira instead to a released version.

I'll try to write some unit tests for them as soon as possible as this seems to be the issue why they are not merging it yet.

**Comment by jozseftiborcz** [comment]
I have run into the same problem with the following setup: JIRA is 9.4.0 onprem DC version, defectdojo is 2.19.4. 

The code here: https://github.com/DefectDojo/django-DefectDojo/blob/2.19.4/dojo/jira_link/helper.py#L990 branches to onprem installation but jira library version 3.4.1 (from requirements.txt) does not support createmeta_issuetypes. The support exists on jira project master but no new release yet.

**Comment by pna-nca** [comment]
> I have run into the same problem with the following setup: JIRA is 9.4.0 onprem DC version, defectdojo is 2.19.4.
> 
> The code here: https://github.com/DefectDojo/django-DefectDojo/blob/2.19.4/dojo/jira_link/helper.py#L990 branches to onprem installation but jira library version 3.4.1 (from requirements.txt) does not support createmeta_issuetypes. The support exists on jira project master but no new release yet.

Hi @jozseftiborcz , what we are doing now to implement a workaround for this problem is altering "requirements.txt" locally:

```
gunicorn==20.1.0
html2text==2020.1.16
humanize==4.6.0
jira==3.4.1
# jira==3.4.1
# installing a package from VCS requires build tools as well
setuptools_scm
wheel
-e git+https://github.com/pmilosev/pycontribs-jira.git@createmeta-deprecation#egg=jira
PyGithub==1.57
lxml==4.9.2
Markdown==3.4.1
```

**Comment by frost9i** [comment]
Thank you for sharing your solution. Worked for my case with Jira v9.2.0

**Comment by r0bag** [comment]
Well, I wanted create a nice POC with the JIRA cloud version:
```
  "version": "1001.0.0-SNAPSHOT",
  "versionNumbers": [
    1001,
    0,
    0
  ],
  "deploymentType": "Cloud",
  "buildNumber": 100247,
```
but I am also receiving "Failed retrieving field metadata from Jira version: (1001, 0, 0),"
Any suggestion for this?

**Comment by nuget1991** [comment]
The same issue 
"Failed retrieving field metadata from Jira version: (8, 13, 27), project: ATTACK, issue type: Task. Misconfigured default issue type ? "

Any sollution guys?

**Comment by gastonbarbaccia** [comment]
Hi,
The same issue in Jira version (1001, 0, 0).
"Failed retrieving field metadata from Jira version: (1001, 0, 0), project: DEV, issue type: Bug. Project misconfigured or no permissions in Jira ?"
Any workaround?

**Comment by mtesauro** [comment]
What version of DefectDojo are you using?

FWIW, I have the latest (2.37.0) connected to Jira cloud without issues so I know its possible.  I'd double check your configuration - Jira can be 'interesting' because of how customizable it is.  Usually when people have trouble, it's a misconfiguration.

HTH
