### ISSUE TITLE
create a database on a separate server

### ISSUE THREAD

**Issue by samira-karimi-elfiman** [DefectDojo/django-DefectDojo#7438]
hi

According to defectdojo architecture, is it possible to create a database on a separate server?
My goal is to install MySQL on a centos Linux server and I don't want the database to be Docker.

Thank you

**Comment by mtesauro** [comment]
There's an example of doing an external DB example with CentOS here:
https://github.com/DefectDojo/Community-Contribs/tree/master/CentOS-7-deploy

It uses PostgreSQL instead of MySQL but it's very possible to have a separate DB - you just need the DD_DATABASE_URL point to that external DB.  You're also responsible for setting up the DB, creating a user and empty database, network connectivity, etc...
