### ISSUE TITLE
Bulk delete older findings via API

### ISSUE THREAD

**Issue by scott86** [DefectDojo/django-DefectDojo#8090]
It would be nice if one were able to perform bulk deletions of findings through the API.  For example, say I want to delete all findings whose publish_date is more than a year ago.  I'd currently have to query for all findings, then inspect each finding's publish_date, compare to X, then delete each older finding individually.

If there is currently a more efficient way to do what I'm describing please let me know.

**Comment by scott86** [comment]
@mtesauro The ability to bulk-delete findings with a date range criteria would be very useful for my project.  I could try to do a PR that adds that capability, if you're open to it.

**Comment by mtesauro** [comment]
@scott86 I had a conversation with the majority of the maintainers on this because we're trying to keep changes to a minimum while we work on DefectDojo 3.0 (details on that [here](https://github.com/DefectDojo/django-DefectDojo/discussions/8002)).

Generally the idea makes sense and I've added the 'consider for 3.0' label so it doesn't get forgotten.

Thanks for the offer to do the PR - when we get closer to 3.0, you may just get a tap on the shoulder. :wink:
