### ISSUE TITLE
uwsgi.sock failed (2: No such file or directory)

### ISSUE THREAD

**Issue by gulsezim11** [DefectDojo/django-DefectDojo#8159]
Hello!

I am deploying defectdojo using Kubernetes, when doing Kubectl apply, the pod is resulting with CrashLoopBackOff status.
`defectdojo-defectdojo-django-6db5dd48b6-xz9kz         0/2     CrashLoopBackOff`

The error itself, I am doing it in Minikube:
`2023/05/25 18:24:08 [crit] 17#17: *185 connect() to unix:///run/defectdojo/uwsgi.sock failed (2: No such file or directory) while connecting to upstream, client: 10.244.0.1, server: , request: "GET /uwsgi_health HTTP/1.1", upstream: "uwsgi://unix:///run/defectdojo/uwsgi.sock:", host: "defectdojo.corporate.domain.local"
10.244.0.1 - - [25/May/2023:18:24:08 +0600] "GET /uwsgi_health HTTP/1.1" 502 497 "-" "kube-probe/1.26" "-"`

When I want to get to the pod with kubectl --exec, it is showing:
`Defaulted container "uwsgi" out of: uwsgi, nginx
error: unable to upgrade connection: container not found ("uwsgi")`

I am not able to find the root issue, help me please

**Comment by gulsezim11** [comment]
fixed

**Comment by gulsezim11** [comment]
@andy2809 hi, I don't remember exactly, but I guess, the problem was celery pool type. I changed the celery pool type from prefork to solo. Also, try to check allowed_hosts value. I am sorry, I forgot to update the issue immediately after fixing it, now I don't remember what fixed it clearly.

**Comment by kiblik** [comment]
This issue was referenced again in https://owasp.slack.com/archives/C2P5BA8MN/p1717610692898139 so I decided to write couple of words for future investigators of this issue.
Error log `unix:///run/defectdojo/uwsgi.sock failed (2: No such file or directory)` from `nginx` container refers to the fact that `uwsgi` contain does not prepare socket (which `nginx` can consume). There might be different reasons.
Use `kubectl logs defectdojo-django-... -c uwsgi` to investigate more. If the container was already killed and logs of the running container are not available, add use `--previous=true` to find an issue in the last alive container.

**Comment by kiblik** [comment]
> following @gulsezim11 "intructions".
> 
> This fixed for me :
> 
> ```
> celery:
>    worker:
>       [...]
>       app_settings:
>          pool_type: prefork
>          autoscale_min: 2
>          autoscale_max: 8
>          concurrency: 8
>          prefetch_multiplier: 128
> ```

This solution raises questions for me. Why it helps? @gulsezim11 describes the issue with `uwsgi` but you are offering a solution that increases the performance of `celeryworker` which is a different component. I'm not sure how fast processing in `celeryworker` might fix communication between `nginx` and `uwsgi`. I'm quite curious.

**Comment by Siryu6** [comment]
Hey @kiblik,

TBH it felt like some black wizard magic as it seems to have no link 🤷‍♂️.
I setup some reminder to investigate further when I come back from holidays I'll keep you up-to-date if I find something interesting.
