### ISSUE TITLE
Title Deduplication

### ISSUE THREAD

**Issue by JohnWickAppSec** [DefectDojo/django-DefectDojo#826]
### Issue Type 
- [ ] Bug
- [X] Enhancement

### Description
I have noticed that DefectDojo will mark findings as duplicates if the first two words in the title are the same. Regardless if the rest of the title is different. For example the findings "Weak SSL Protocol" and "Weak SSL Ciphers" are being marked as duplicate findings. I would like DefectDojo to analyze the entire title and not just the first two words of the title.

**Comment by drdsec** [comment]
Perhaps this Dojo API script will help? It merges findings with identical titles. To use this script, set the engagement product ID in the URL.

[mergebytitle.py.txt](https://github.com/DefectDojo/django-DefectDojo/files/2912545/mergebytitle.py.txt)

**Comment by devGregA** [comment]
I believe it is matching CWE here rather than title. For DD to dedupe on titles they must be exactly the  same. There is a PR open that has numerous dedupe improvements https://github.com/DefectDojo/django-DefectDojo/pull/1043 which should be merged this week. Please feel free to reopen if you continue to have issues.
