### ISSUE TITLE
Difference between Paused & Active Engagement

### ISSUE THREAD

**Issue by adrianasantex** [DefectDojo/django-DefectDojo#8657]
Hi,

I have been researching in the docs and I am not finding which is the difference between paused and active engagement and how to manage them throught the app. Could someone help me?

Thanks'!

**Comment by mtesauro** [comment]
@adrianasantex Basically, it's what the labels say:

An active engagement has someone working on it currently - it's being actively worked

A paused engagement is one that has been put on hold - it's not actively being worked but is likely to be re-activated in the future.

These distinctions were primarily used for manual assessment work like pen tests or other things done by humans rather than scanners.  Though you could internally define a "Something Engagement" as running 7 different scanner against some target. Then you could have an active engagement while you run the first 5 tools until something happens that pulls you off that work to something else. You'd set the engagement to paused while your away.  When you come back to run those remaining 2 scans, you'd change the engagement to active.
