### ISSUE TITLE
Simple-Search does not find products with a dash e.g. "foo-bar"

### ISSUE THREAD

**Issue by xthk** [DefectDojo/django-DefectDojo#881]
### Issue Type 
- [X] Bug
- [ ] Enhancement

### Description

If a search term includes a dash "-" simple search does not show a matching product.

Example:  ```/simple_search?query=foo-bar```

If there is a finding with that name, it is found.

### Operating System

Ubuntu 16.04

### Install

- [ ] setup.bash
- [ ] docker
- [X] custom

### DefectDojo Version

1.5.2

### Steps to Reproduce

- Create a product named "foo-bar"
- Insert "foo-bar" into "simple search": ```/simple_search?query=foo-bar```

**Comment by propersam** [comment]
I wanted to fix this issue, and then I saw the line that cleans the input before sending query to database.

This is not an error. It happens for security sake. if '-' is allowed in simple_search, It's going to be vulnerable to sql Injection

**Comment by propersam** [comment]
But I think hypen('-') should have never been allowed as a valid string for product name in the first place. This still posses some potential (less-likely) second order injection vulnerability

**Comment by propersam** [comment]
@aaronweaver can I implement stripping off '-' (or replacing '-' with '_' )before storing product name for the sake of avoiding this issue with simple_search.

'_' works just fine with product name

**Comment by aaronweaver** [comment]
Hi @propersam, I'd rather figure out how to do it in the search. I'd look up Watson for python and figure out how to escape that. I'm pretty we can't be the only ones.

```
 products = watson.search(clean_query, models=(
                        Product.objects.filter(authorized_users__in=[
                            request.user]),))
```

**Comment by propersam** [comment]
Let me look into it and see what I can do

**Comment by madchap** [comment]
Could it be related to https://github.com/etianen/django-watson/issues/223 ?

**Comment by devEricA** [comment]
I think this is indeed related to https://github.com/etianen/django-watson/issues/223. When I was investigating this issue, I created two products: dash-product and foo-bar, giving each one the description “For use with search”. Using the simple search to pull up these two products resulted in unexpected results; Typing foo-bar in the search bar failed to pull up the product foo-bar, but typing dash-product in the search bar successfully pulled the product dash-product. To further complicate things, typing in search in the search bar successfully pulled up both products (intended since both products had search in their description)

**Comment by valentijnscholten** [comment]
In #2861 I am working on some search improvements and am trying to make this work, but MySQL is really weird regarding hyphens, also see https://github.com/etianen/django-watson/issues/237
However, in the current WIP version of my PR I can finding products called `eindhoven-airport` for example. Basically `foo-bar` is the only example I can find that is not working 🤔
