### ISSUE TITLE
cant find sso settings in my local defectdojo panel

### ISSUE THREAD

**Issue by peeqonet** [DefectDojo/django-DefectDojo#8816]
I was reading the following documents, but I did not find the page related to sso settings.

https://documentation.defectdojo.com/proprietary_plugins/01_plus/tuner/#sso-settings

**Comment by mtesauro** [comment]
@peeqonet  The URL and section that documents is in say that they are part of what comes with the DefectDojo commercial SaaS offering - that's why there's a `proprietary_plugins` in the URL and that doc is under a section called "Proprietary Plugins". You will find those options if you have a SaaS instance.

If your curious what the SaaS offering has, you can see https://www.defectdojo.com/ for details.
