### ISSUE TITLE
Documentation running in production not working

### ISSUE THREAD

**Issue by Luiggy** [DefectDojo/django-DefectDojo#945]
### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description
Could not make it run following the instructions on the documentation of production environment.

### Operating System 
Ubuntu 18.04.2 LTS 
Linux 4.15.0-20-generic x86_64
### Install

- [x] setup.bash
- [ ] docker

### DefectDojo Version 
Latest pull from git repository (e8c152a) 

### Steps to Reproduce
I did follow steps on [running in production](https://defectdojo.readthedocs.io/en/latest/running-in-production.html)
tried by default with Django version 1.11.19 in a virtual env but not successfull.
got the same issue if i use Django 2.1.7 and use pip3 along with python 3.
When executing `celery -A dojo worker -l info --concurrency 3 &`
it gives me the following error message 

### Screenshots 
![2019-03-19 01_26_49-DOjo](https://user-images.githubusercontent.com/1401734/54572182-796cf400-49e6-11e9-95bf-8f3772a4633b.png)

**Comment by aaronweaver** [comment]
Try out the docker or kubernetes, we are working on updating that right now.

**Comment by Luiggy** [comment]
Thanks, I will in the meantime use the docket installation.

**Comment by dragos-sh** [comment]
@devEricA @aaronweaver Hi guys, do you have an updated version of how we can run this one on production? The current one does not work tbh because some bits and pieces are not accurate or might be obsolete. 

The truth is we have tested/evaluated this product having it deployed it on various configurations and: 

1. If we are deploying this with the  AWS ECS things are getting quite interesting, The current docker-compose.yml file has to be tweaked appropriately to have the deployment working. While the initial deployment succeeded, from some whatever unknown reasons, all the DefectDojo docker ECS instances are getting restarted after 1 minute. It seems this is happening because of something related to the current MySQL instance/volume. A solution would be to replace the existing MySQL DB with PostgreSQL DB which is much friendly. This is a WIP for us. 

2. We did not use ECS and have deployed the product by tweaking the provided AWS architecture. I think @aaronweaver has a repo for that. It worked somehow but did not scale well under heavy usage. Still investigating why.  

Down to the bottom, we would like trying deploying this product as standalone in production too by following updated documentation. We know there might be the HELM option also but the AWS EKS option is still something more close to an advanced beta feature and GPC is not an option for us just yet. 

Thank you!

**Comment by alekorn102** [comment]
alguien pudo levantar en produccion defect-dojo?

**Comment by bharathgajendran** [comment]
Hey @dragos-sh can you please share details on how you got this up and running on ECS, if you can share the documentation or link on steps involved in making this up and running in ECS that will be really helpful, thank you!
