### ISSUE TITLE
Security Scans passed for Defect Dojo

### ISSUE THREAD

**Issue by joelppr** [DefectDojo/django-DefectDojo#9587]
Good morning,
 
We would like to ask you about what security analysis you perform on your Open Source projects (for example this one) as we have seen that in the actions we do not find security checks (such as dependencies, secrets, code bugs, copyright, etc) and we would like to know if at CICD level this kind of checks are passed by other means and, if so, how would it be done?
 
Thank you in advance

**Comment by manuel-sommer** [comment]
As far as I know DefectDojo is part of a Bug bounty program. Is this right @mtesauro ?
Maybe you should rather ask in the OWASP slack channel as this is rather a support question and not an issue related with the code. 
Can we close this issue @mtesauro ?

**Comment by mtesauro** [comment]
We have a Bug Bounty in placed - details at https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/SECURITY.md

We also run [renovate](https://github.com/DefectDojo/django-DefectDojo/pulls?q=is%3Apr+is%3Aclosed+author%3Aapp%2Frenovate) and [dependabot](https://github.com/DefectDojo/django-DefectDojo/pulls?q=is%3Apr+is%3Aclosed+author%3Aapp%2Fdependabot) - examples of those are easy to find in the closed PRs.

We have other tools which run on PRs such as:

* [ruff linter](https://github.com/DefectDojo/django-DefectDojo/actions/workflows/ruff.yml)
* [flake8](https://github.com/DefectDojo/django-DefectDojo/actions/workflows/flake8.yml)
* [ShellCheck](https://github.com/DefectDojo/django-DefectDojo/actions/workflows/differential-shellcheck.yml)
* [Helm chart linting](https://github.com/DefectDojo/django-DefectDojo/actions/workflows/test-helm-chart.yml)
* [DryRun Security](https://www.dryrun.security/) - runs on every PR, configuration is [here](https://github.com/DefectDojo/django-DefectDojo/blob/master/.dryrunsecurity.yaml)
* We also have many unit and other GH Action tests which happen on every PR some of which cover security aspects:
![image](https://github.com/DefectDojo/django-DefectDojo/assets/3422419/9e45feb6-8ac6-4703-a01a-fce1555c5957)

"Normal" PR take 4 approvals before they are merged
"Library/Container" PRs (mostly dependabot & renovate) require 2 PRs since they are just updating component versions.

HTH

**Comment by cktricky** [comment]
Hey @joelppr 👋 ,

Also wanted to add here that, we (DryRun Security) have been **SILENTLY** running SAST style checks for the last few weeks on Defect Dojo (testing pre-ship to ensure accurate runs, etc.) and those tests have gone well.  So, with that in mind, this week we should start surfacing SAST style results here in Defect Dojo as well as shipping v2 of our HIGHLY improved analyzers that indicate potential for risk (sens func/files). 

Expect more and more analyzers to come online with better and better results.
