### ISSUE TITLE
AzureAD/EntraID Authentication for database backend

### ISSUE THREAD

**Issue by vosdev** [DefectDojo/django-DefectDojo#9610]
**Is your feature request related to a problem? Please describe**
As a DevSecOps engineer I am required by security policy to authenticate database connections using Active Directory / EntraID instead of native postgresql user and password.

**Describe the solution you'd like**
The possibility to use Azure AD token based authentication for database connectivity

**Describe alternatives you've considered**
None. This is a new company policy.

**Additional context**
https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-azure-ad-authentication

https://stackoverflow.com/questions/77135512/sqlalchemy-connect-to-azure-postgresql-flexible-database-with-token-authenticati

**Comment by mtesauro** [comment]
@vosdev 
Your best option short of maintaining a fork of DefectDojo with Azure specific changes is to use something like PgBouncer and have DefectDojo connect to that (locally if you're doing a compose install). Then have PgBouncer connect to the "real" DB. 

PgBouncer apparently supports Azure / AD auth - though I have zero experience doing that.

https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-pgbouncer

Given that this auth is vendor specific and would be problematic to test and maintain, I don't see DefectDojo doing that auth until the Django framework supports it.

HTH

**Comment by vosdev** [comment]
Thank you Matt :)

We will look at alternative options to keep using DefectDojo.

**Comment by nareshbogathi** [comment]
@mtesauro  I wanted to revisit this topic as we’re currently blocked by an internal compliance requirement.
We have an Azure policy (AAB Database for PostgreSQL Flexible Server - Entra ID Password Authentication v2) that enforces the use of Entra ID–based authentication instead of username/password. Our PostgreSQL flexible server is flagged as non-compliant until this is resolved.

Because of this, we’re unable to use standard credentials for DefectDojo database connectivity.
Has there been any progress or reconsideration around supporting Azure Entra ID (AAD) / token-based authentication for PostgreSQL connections? Or is PgBouncer still the only recommended workaround in this scenario?

This is becoming a blocker for us to remain compliant while continuing to use DefectDojo, so any updates or guidance would be greatly appreciated.

Thanks!
