### ISSUE TITLE
OpenAPI 3 docs not showing example values

### ISSUE THREAD

**Issue by quirinziessler** [DefectDojo/django-DefectDojo#9629]
When looking at the Swagger (OpenAPI 3) docs, I noticed that for a bunch of api calls the example and also acceptable values are missing and just "string" is shown.
The issue is showing up on v2.28.0 and on the latest dev version. Versions between may also be affected.

Below some examples:
![image](https://github.com/DefectDojo/django-DefectDojo/assets/19915467/4f60c849-fe20-46d7-a488-83ba4d81c724)
![image](https://github.com/DefectDojo/django-DefectDojo/assets/19915467/0452313b-c8f3-4b92-88f5-7886260f510d)
![image](https://github.com/DefectDojo/django-DefectDojo/assets/19915467/62938f35-42d1-43e5-9d4d-e8e186769897)
![image](https://github.com/DefectDojo/django-DefectDojo/assets/19915467/aad5356b-65f5-4736-aea0-20ef8ccad715)

**Comment by macsoun** [comment]
same thing on v2.31.1

**Comment by Stamka** [comment]
all the same v2.28.3

**Comment by manuel-sommer** [comment]
@kiblik do you have any idea on this?

**Comment by kiblik** [comment]
## Short answer
no idea

## Long answer

None of the Dojo models specify examples in schemas ([as it is officially documented](https://swagger.io/docs/specification/adding-examples/)) right now.
It is used only in `Paginated` OpenAPI definitions (usually `GET` without ID). I suppose it is added by a standard rendering mechanism.

So I expected that if you can see some examples (e.g. `credentials`), they are generated by swagger-ui based on a definition of a schema.

I thought that they were not generated in some cases (e.g. `engagements`) because of some less standard schemas (e.g. mix arrays of strings and nulls - `engagement_type`).
However the same is happening in more standard but customized scenarios (e.g. I excluded `['date', 'mitigated_by']` from `EndpointStatusSerializer` so it used only booleans and integers but it was still failing).

So to be honest, I do not know.

**Comment by Maffooch** [comment]
@kiblik When I set the swagger UI to use def-spectacular-sidecar (set in #9118) I have useful example schemas and and response bodies again. I am not sure if this is a complete solution, but I have eyeballed each endpoint and everything looks alright. Here is all I did:
```
# If true, drf-spectacular will load CSS & JS from default CDN, otherwise from static resources
DD_DEFAULT_SWAGGER_UI=(bool, False), # Changed from True -> False
```
I'd be happy to throw up a PR flipping the default if there is consensus that this a good way forward

**Comment by kiblik** [comment]
Ok. Thank you @Maffooch. Now I see what is happening.

At first, all versions of DD are automatically (if you do not set `DD_DEFAULT_SWAGGER_UI=False`) using `latest` swagger pulled from public CDN.

## Analysis about `DD_DEFAULT_SWAGGER_UI=False`

Latest DDs (`2.31.0`..`2.31.4`) are using `drf-spectacular-sidecar` in version `2024.2.1`

https://github.com/DefectDojo/django-DefectDojo/blob/c5d896b2a606985f41669388962e47409f4866ba/requirements.txt#L77

Which contains `swagger-ui-dist` in version `5.11.2`

https://github.com/tfranzel/drf-spectacular-sidecar/blob/a383edc500b370c00e521efc8b17e6267234f3fd/distributions.json#L3

I expect that new version of `drf-spectacular-sidecar` will be automatically released of March 1st as version `2024.3.1` with `swagger-ui-dist` in version `5.11.8` or `5.11.9`

Version `5.11.2` works fine (in the context of this issue, I have no knowledge of the rest of this tool).

## Analysis about `DD_DEFAULT_SWAGGER_UI=True` (default config)

I came through recently released versions (you can do it by yourself by adding `SPECTACULAR_SETTINGS['SWAGGER_UI_DIST'] = 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.11.8'` to `settings.py`). I found out that `5.11.7` works well and `5.11.8` (version released 5 days ago) is showing `"string"` instead of the definition as json.

## Next steps/workaround

- Using `DD_DEFAULT_SWAGGER_UI=False` will help to fix urgent problems. But it is not a long-term solution.
- I propose to open an issue in https://github.com/swagger-api/swagger-ui/issues (there is not this kind of issue from the last 5 days).
- For DD moderators: If the new version of `drf-spectacular-sidecar` will be released (it might be soon and it might be offered by dependabot) with `swagger-ui-dist` in version `5.11.8`, I recommend not merging it (for now) because it would break instances for everybody who uses `DD_DEFAULT_SWAGGER_UI=False`

**Comment by Maffooch** [comment]
Excellent analysis! I agree with what you have proposed here. I will keep my eyes open for sidecar updates coming from dependably/renovate

I thought I was going crazy for a minute there because I was so confident #9108 was good to go when it was merged 😅

**Comment by kiblik** [comment]
(edit) I propose to open an issue in https://github.com/swagger-api/swagger-ui/issues (there is not this kind of issue from the last 5 days). Issues already is already open https://github.com/swagger-api/swagger-ui/issues/9645

**Comment by kiblik** [comment]
Good news everyone: https://github.com/swagger-api/swagger-ui/issues/9645

**Comment by kiblik** [comment]
⚠️ my concerns become true: `drf-spectacular-sidecar` was released in version `2024.3.1` with broken `swagger-ui-dist` in version `5.11.8`.
I recommend, not merging mentioned version otherwise `DD_DEFAULT_SWAGGER_UI=False` will have an "opposite" outcome.

But still we can ask to release some version of  `drf-spectacular-sidecar` in between only because of this fix.

**Comment by Maffooch** [comment]
@kiblik thank you so much for taking point on this! I think it would be beneficial to us to roll with sidecar all the time for stability purposes. There would be a change monthly, and we could likely catch things like this before we introduce the changes to dojo.

If someone wanted the absolute latests swagger UI at a given time, they could just toggle that setting and have it

**Comment by kiblik** [comment]
> @kiblik thank you so much for taking point on this! I think it would be beneficial to us to roll with sidecar all the time for stability purposes. There would be a change monthly, and we could likely catch things like this before we introduce the changes to dojo.
> 
> If someone wanted the absolute latests swagger UI at a given time, they could just toggle that setting and have it

Considering how it is evolving, I suppose pinning (acceptance of #9645) will increase the stability of DD.

**Comment by kiblik** [comment]
The bug was fixed in `swagger-ui-dist` in version `5.11.9`. `@latest` is still caching `5.11.8` but I locally tested `5.11.9` and it works well (tested only on `POST engagements`).

Now we are waiting for the new version of `drf-spectacular-sidecar` (https://github.com/tfranzel/drf-spectacular-sidecar/issues/8#issuecomment-1976419472), plus pinning to the local version (#9645).
Might be part of the following DD release (no promises).

**Comment by kiblik** [comment]
New `drf-spectacular-sidecar` is ready #9670

**Comment by mtesauro** [comment]
Handled in #9670 and #9645 so closing
